import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-invoice0505',
  templateUrl: './invoice0505.component.html',
  styleUrls: ['./invoice0505.component.css']
})
export class Invoice0505Component implements OnInit {
  five: any = [
    {
      'Amount - Order Total': 100.7,
      'Item - Name': 'Port Authority® Ladies Core Soft Shell Jacket - X-Large / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 277',
      'Item - Qty': 1,
      'Item - Price': 43.5,
      'Item - SKU': '403239-L317-AVPS-XL',
      'Ship To - Name': 'Laura Hill',
      'Ship To - Address 1': '9701 WILCOX DR',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1061,
      'Date - Shipped Date': '5/5/2021 8:57:08 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 100.7
    },
    {
      'Amount - Order Total': 100.7,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 277',
      'Item - Qty': 1,
      'Item - Price': 24.5,
      'Item - SKU': '403197-PC90H-AWGC-L',
      'Ship To - Name': 'Laura Hill',
      'Ship To - Address 1': '9701 WILCOX DR',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1061,
      'Date - Shipped Date': '5/5/2021 8:57:08 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 100.7
    },
    {
      'Amount - Order Total': 100.7,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt - Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 277',
      'Item - Qty': 2,
      'Item - Price': 9.35,
      'Item - SKU': '403199-PC55LS-AWGC-L',
      'Ship To - Name': 'Laura Hill',
      'Ship To - Address 1': '9701 WILCOX DR',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1061,
      'Date - Shipped Date': '5/5/2021 8:57:08 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 100.7
    },
    {
      'Amount - Order Total': 100.7,
      'Item - Name': 'P&C Core Blend T-Shirt - Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 277',
      'Item - Qty': 2,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-L',
      'Ship To - Name': 'Laura Hill',
      'Ship To - Address 1': '9701 WILCOX DR',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1061,
      'Date - Shipped Date': '5/5/2021 8:57:08 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 100.7
    },
    {
      'Amount - Order Total': 69.5,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo - Medium / Red',
      'Notes - From Buyer': '<br/>Store Number/Name: 212',
      'Item - Qty': 1,
      'Item - Price': 27,
      'Item - SKU': '403275-DG20W-SG-M',
      'Ship To - Name': 'April Burton',
      'Ship To - Address 1': '7085 ROUND HILL DR APT B1',
      'Ship To - Address 2': 'B1',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1062,
      'Date - Shipped Date': '5/5/2021 8:57:08 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 69.5
    },
    {
      'Amount - Order Total': 69.5,
      'Item - Name': 'Devon & Jones Ladies\' CrownLux Performance™ Stretch Tunic - Medium / Navy / Auto-Wares Group of Companies',
      'Notes - From Buyer': '<br/>Store Number/Name: 212',
      'Item - Qty': 1,
      'Item - Price': 42.5,
      'Item - SKU': '403249-DG542W-AWGC-M',
      'Ship To - Name': 'April Burton',
      'Ship To - Address 1': '7085 ROUND HILL DR APT B1',
      'Ship To - Address 2': 'B1',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1062,
      'Date - Shipped Date': '5/5/2021 8:57:08 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 69.5
    },
    {
      'Amount - Order Total': 213,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - Large / Red',
      'Notes - From Buyer': 'Attn Justyn Enyart and Steven Goodroe<br/>Store Number/Name: 277',
      'Item - Qty': 1,
      'Item - Price': 35.5,
      'Item - SKU': '403272-DG20P-AVPS-L',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1063,
      'Date - Shipped Date': '5/5/2021 8:57:08 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 213
    },
    {
      'Amount - Order Total': 213,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - X-Large / Red',
      'Notes - From Buyer': 'Attn Justyn Enyart and Steven Goodroe<br/>Store Number/Name: 277',
      'Item - Qty': 5,
      'Item - Price': 35.5,
      'Item - SKU': '403272-DG20P-AVPS-XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1063,
      'Date - Shipped Date': '5/5/2021 8:57:08 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 213
    },
    {
      'Amount - Order Total': 50.75,
      'Item - Name': 'Devon & Jones Men\'s Three-Season Classic Jacket - Large / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 521',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-AVPS-L',
      'Ship To - Name': 'Jerry Brown',
      'Ship To - Address 1': '6229 CROSS CREEK BLVD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1064,
      'Date - Shipped Date': '5/5/2021 8:57:08 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 50.75
    },
    {
      'Amount - Order Total': 50.5,
      'Item - Name': 'P&C Core Blend T-Shirt - X-Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 500 Madison WI warehouse',
      'Item - Qty': 5,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-XL',
      'Ship To - Name': 'Joe Duane',
      'Ship To - Address 1': '816 W MAIN ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1066,
      'Date - Shipped Date': '5/5/2021 8:57:08 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 50.5
    },
    {
      'Amount - Order Total': 50.5,
      'Item - Name': 'P&C Essential Fleece Crewneck Sweatshirt - X-Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 500 Madison WI warehouse',
      'Item - Qty': 1,
      'Item - Price': 15.5,
      'Item - SKU': '403200-PC90-AWGC-XL',
      'Ship To - Name': 'Joe Duane',
      'Ship To - Address 1': '816 W MAIN ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1066,
      'Date - Shipped Date': '5/5/2021 8:57:08 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 50.5
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Peter Giles',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 356',
      'Ship To - Country': 'US',
      'Order - Number': 1336,
      'Date - Shipped Date': '5/5/2021 8:58:12 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20P-RED',
      'Ship To - Name': 'Eric Bailey',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 623',
      'Ship To - Country': 'US',
      'Order - Number': 1338,
      'Date - Shipped Date': '5/5/2021 8:58:12 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Steve Qualls',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 226',
      'Ship To - Country': 'US',
      'Order - Number': 1341,
      'Date - Shipped Date': '5/5/2021 8:58:12 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Bob Griffes',
      'Ship To - Address 1': '1227 S LINCOLN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTOWARES/STORE277',
      'Ship To - Country': 'US',
      'Order - Number': 1347,
      'Date - Shipped Date': '5/5/2021 8:58:12 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'Jebadiah Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 277',
      'Ship To - Country': 'US',
      'Order - Number': 1345,
      'Date - Shipped Date': '5/5/2021 8:58:12 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Jebadiah Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 277',
      'Ship To - Country': 'US',
      'Order - Number': 1345,
      'Date - Shipped Date': '5/5/2021 8:58:12 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'Jebadiah Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 277',
      'Ship To - Country': 'US',
      'Order - Number': 1345,
      'Date - Shipped Date': '5/5/2021 8:58:12 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'Jebadiah Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 277',
      'Ship To - Country': 'US',
      'Order - Number': 1345,
      'Date - Shipped Date': '5/5/2021 8:58:12 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'Jebadiah Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 277',
      'Ship To - Country': 'US',
      'Order - Number': 1345,
      'Date - Shipped Date': '5/5/2021 8:58:12 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20P-RED',
      'Ship To - Name': 'Salvatore Ciardo',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 617',
      'Ship To - Country': 'US',
      'Order - Number': 1349,
      'Date - Shipped Date': '5/5/2021 8:58:12 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies Cooling Performance T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-NW3201-Graphite',
      'Ship To - Name': 'Chelsea Carigon',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 101',
      'Ship To - Country': 'US',
      'Order - Number': 1351,
      'Date - Shipped Date': '5/5/2021 8:58:12 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Crewneck Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90-Charcoal',
      'Ship To - Name': 'Chelsea Carigon',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 101',
      'Ship To - Country': 'US',
      'Order - Number': 1351,
      'Date - Shipped Date': '5/5/2021 8:58:12 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    }
  ];

  constructor() { }

  ngOnInit(): void {
  }

  // tslint:disable-next-line:typedef
  downloadFile(data: any) {
    const replacer = (key, value) => (value === null ? '' : value); // specify how you want to handle null values here
    const header = Object.keys(data[0]);
    const csv = data.map((row) =>
      header
        .map((fieldName) => JSON.stringify(row[fieldName], replacer))
        .join(',')
    );
    csv.unshift(header.join(','));
    const csvArray = csv.join('\r\n');
    const a = document.createElement('a');
    const blob = new Blob([csvArray], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    a.href = url;
    a.download = 'Shipments-05-05.csv';
    a.click();
    window.URL.revokeObjectURL(url);
    a.remove();
  }

  public removeSlashes(side: string): string {
    if (side) {
      side.replace(/\//g, '');
      return side.replace('<br/>', '');
    }
  }

}
