import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-invoice0506',
  templateUrl: './invoice0506.component.html',
  styleUrls: ['./invoice0506.component.css']
})
export class Invoice0506Component implements OnInit {
  six: any = [
    {
      'Amount - Order Total': 187.5,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - 2XL / Red',
      'Notes - From Buyer': '<br/>Store Number/Name: 340',
      'Item - Qty': 5,
      'Item - Price': 37.5,
      'Item - SKU': '403272-DG20P-AVPS-2XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1065,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 187.5
    },
    {
      'Amount - Order Total': 106.5,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - X-Large / Red',
      'Notes - From Buyer': '<br/>Store Number/Name: 286',
      'Item - Qty': 3,
      'Item - Price': 35.5,
      'Item - SKU': '403272-DG20P-AVPS-XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1067,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 106.5
    },
    {
      'Amount - Order Total': 50.75,
      'Item - Name': 'Devon & Jones Men\'s Three-Season Classic Jacket - Large / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 639',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-BTB-L',
      'Ship To - Name': 'Cole Green',
      'Ship To - Address 1': '104 S MONROE ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1072,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 50.75
    },
    {
      'Amount - Order Total': 52.75,
      'Item - Name': 'Devon & Jones Men\'s Three-Season Classic Jacket - 2XL / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 362',
      'Item - Qty': 1,
      'Item - Price': 52.75,
      'Item - SKU': '403195-D700-AVPS-2X',
      'Ship To - Name': 'Brenda Hudgen',
      'Ship To - Address 1': '317 W PROSPECT ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1071,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 52.75
    },
    {
      'Amount - Order Total': 52.75,
      'Item - Name': 'Devon & Jones Men\'s Three-Season Classic Jacket - 2XL / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 265',
      'Item - Qty': 1,
      'Item - Price': 52.75,
      'Item - SKU': '403195-D700-AVPS-2X',
      'Ship To - Name': 'Thomas Isenga',
      'Ship To - Address 1': '488 BAY PARK DR',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1070,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 52.75
    },
    {
      'Amount - Order Total': 50.75,
      'Item - Name': 'Devon & Jones Men\'s Three-Season Classic Jacket - Large / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 507',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-AVPS-L',
      'Ship To - Name': 'Steven Moelker',
      'Ship To - Address 1': '2665 84TH ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1068,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 50.75
    },
    {
      'Amount - Order Total': 28,
      'Item - Name': 'P&C Core Blend T-Shirt - X-Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: Coldwater',
      'Item - Qty': 4,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-XL',
      'Ship To - Name': 'Tara  Sturgeon',
      'Ship To - Address 1': '327 BOISMIER LN',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1073,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 28
    },
    {
      'Amount - Order Total': 127,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo - 2XL / Red',
      'Notes - From Buyer': '<br/>Store Number/Name: AV 521 Holly Hieber',
      'Item - Qty': 2,
      'Item - Price': 35,
      'Item - SKU': '403275-DG20W-AVPS-2XL',
      'Ship To - Name': 'Holly Hieber',
      'Ship To - Address 1': '4340 BRUICK RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1074,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 127
    },
    {
      'Amount - Order Total': 127,
      'Item - Name': 'Devon & Jones Ladies\' CrownLux Performance™ Stretch Tunic - 2XL / Navy / Auto Value Parts Stores',
      'Notes - From Buyer': '<br/>Store Number/Name: AV 521 Holly Hieber',
      'Item - Qty': 1,
      'Item - Price': 44.5,
      'Item - SKU': '403249-DG542W-AVPS-2X',
      'Ship To - Name': 'Holly Hieber',
      'Ship To - Address 1': '4340 BRUICK RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1074,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 127
    },
    {
      'Amount - Order Total': 127,
      'Item - Name': 'Ladies Cooling Performance T-Shirt - 2XL / Graphite',
      'Notes - From Buyer': '<br/>Store Number/Name: AV 521 Holly Hieber',
      'Item - Qty': 1,
      'Item - Price': 12.5,
      'Item - SKU': '403196-NW3201-AWGC-2X',
      'Ship To - Name': 'Holly Hieber',
      'Ship To - Address 1': '4340 BRUICK RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1074,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 127
    },
    {
      'Amount - Order Total': 21,
      'Item - Name': 'P&C Core Blend T-Shirt - X-Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 837',
      'Item - Qty': 3,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-XL',
      'Ship To - Name': 'Robert Bunting',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1075,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 21
    },
    {
      'Amount - Order Total': 50.75,
      'Item - Name': 'P&C Core Blend T-Shirt - 3XL / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 330',
      'Item - Qty': 5,
      'Item - Price': 10.15,
      'Item - SKU': '403198-PC55-AWGC-3X',
      'Ship To - Name': 'CHAD BOWER',
      'Ship To - Address 1': '507 E AVENUE B',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1076,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 50.75
    },
    {
      'Amount - Order Total': 21,
      'Item - Name': 'P&C Core Blend T-Shirt - Large / Charcoal',
      'Notes - From Buyer': 'Store 244',
      'Item - Qty': 1,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-L',
      'Ship To - Name': 'Chris Rohder',
      'Ship To - Address 1': '4980 PARK LAKE RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1077,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 21
    },
    {
      'Amount - Order Total': 21,
      'Item - Name': 'P&C Core Blend T-Shirt - X-Large / Charcoal',
      'Notes - From Buyer': 'Store 244',
      'Item - Qty': 2,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-XL',
      'Ship To - Name': 'Chris Rohder',
      'Ship To - Address 1': '4980 PARK LAKE RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1077,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 21
    },
    {
      'Amount - Order Total': 37.5,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - 2XL / Red',
      'Notes - From Buyer': '<br/>Store Number/Name: 298',
      'Item - Qty': 1,
      'Item - Price': 37.5,
      'Item - SKU': '403272-DG20P-AVPS-2XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1081,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 37.5
    },
    {
      'Amount - Order Total': 61.85,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - X-Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 608',
      'Item - Qty': 1,
      'Item - Price': 24.5,
      'Item - SKU': '403197-PC90H-AWGC-XL',
      'Ship To - Name': 'Steve Labean',
      'Ship To - Address 1': '2222 LIPPINCOTT BLVD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1080,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 61.85
    },
    {
      'Amount - Order Total': 61.85,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt - X-Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 608',
      'Item - Qty': 1,
      'Item - Price': 9.35,
      'Item - SKU': '403199-PC55LS-AWGC-XL',
      'Ship To - Name': 'Steve Labean',
      'Ship To - Address 1': '2222 LIPPINCOTT BLVD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1080,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 61.85
    },
    {
      'Amount - Order Total': 61.85,
      'Item - Name': 'P&C Core Blend T-Shirt - X-Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 608',
      'Item - Qty': 4,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-XL',
      'Ship To - Name': 'Steve Labean',
      'Ship To - Address 1': '2222 LIPPINCOTT BLVD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1080,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 61.85
    },
    {
      'Amount - Order Total': 106.5,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - X-Large / Red',
      'Notes - From Buyer': '<br/>Store Number/Name: 608',
      'Item - Qty': 3,
      'Item - Price': 35.5,
      'Item - SKU': '403272-DG20P-AVPS-XL',
      'Ship To - Name': 'Steve Labean',
      'Ship To - Address 1': '2222 LIPPINCOTT BLVD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1079,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 106.5
    },
    {
      'Amount - Order Total': 98.23,
      'Item - Name': 'Men\'s Cooling Performance T-Shirt - 2XL / Graphite',
      'Notes - From Buyer': 'These items are for worker #22180 , He will pay for or said items.<br/>Store Number/Name: 307',
      'Item - Qty': 4,
      'Item - Price': 12.5,
      'Item - SKU': '403201-N3142-AWGC-2XL',
      'Ship To - Name': 'Auto value Store 307',
      'Ship To - Address 1': '1367 N LEROY ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1083,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 98.23
    },
    {
      'Amount - Order Total': 98.23,
      'Item - Name': 'Port Authority® Core Soft Shell Jacket - 2XL / Black',
      'Notes - From Buyer': 'These items are for worker #22180 , He will pay for or said items.<br/>Store Number/Name: 307',
      'Item - Qty': 1,
      'Item - Price': 45.5,
      'Item - SKU': '403203-J317-AVPS-2X',
      'Ship To - Name': 'Auto value Store 307',
      'Ship To - Address 1': '1367 N LEROY ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1083,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 98.23
    },
    {
      'Amount - Order Total': 50.75,
      'Item - Name': 'Devon & Jones Ladies Three-Season Classic Jacket - Large / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 511',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403277-D700W-AVPS-L',
      'Ship To - Name': 'Cynthia Emmert',
      'Ship To - Address 1': '0-217 Lake Michigan',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1084,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 50.75
    },
    {
      'Amount - Order Total': 75,
      'Item - Name': 'Women\'s Windsor Henley - X-Large / Grey/White Stripe / Auto-Wares Group of Companies',
      'Notes - From Buyer': 'STORE 147',
      'Item - Qty': 1,
      'Item - Price': 32.5,
      'Item - SKU': '403250-2913-AWGC-XL',
      'Ship To - Name': 'Kelly Garrison',
      'Ship To - Address 1': '11832 TWIN BROOK DR',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1086,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 75
    },
    {
      'Amount - Order Total': 75,
      'Item - Name': 'Devon & Jones Ladies\' CrownLux Performance™ Stretch Tunic - X-Large / Navy / Auto-Wares Group of Companies',
      'Notes - From Buyer': 'STORE 147',
      'Item - Qty': 1,
      'Item - Price': 42.5,
      'Item - SKU': '403249-DG542W-AWGC-XL',
      'Ship To - Name': 'Kelly Garrison',
      'Ship To - Address 1': '11832 TWIN BROOK DR',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1086,
      'Date - Shipped Date': '5/6/2021 6:57:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 75
    },
    {
      'Amount - Order Total': 57.5,
      'Item - Name': 'Men\'s Cooling Performance T-Shirt - X-Large / Graphite',
      'Notes - From Buyer': '<br/>Store Number/Name: 330',
      'Item - Qty': 2,
      'Item - Price': 9.5,
      'Item - SKU': '403201-N3142-AWGC-XL',
      'Ship To - Name': 'Nathan Livermore',
      'Ship To - Address 1': 'N7854 BORGSTROM RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1078,
      'Date - Shipped Date': '5/6/2021 7:03:33 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 57.5
    },
    {
      'Amount - Order Total': 57.5,
      'Item - Name': 'P&C Core Blend T-Shirt - X-Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 330',
      'Item - Qty': 2,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-XL',
      'Ship To - Name': 'Nathan Livermore',
      'Ship To - Address 1': 'N7854 BORGSTROM RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1078,
      'Date - Shipped Date': '5/6/2021 7:03:33 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 57.5
    },
    {
      'Amount - Order Total': 57.5,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - X-Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 330',
      'Item - Qty': 1,
      'Item - Price': 24.5,
      'Item - SKU': '403197-PC90H-AWGC-XL',
      'Ship To - Name': 'Nathan Livermore',
      'Ship To - Address 1': 'N7854 BORGSTROM RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1078,
      'Date - Shipped Date': '5/6/2021 7:03:33 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 57.5
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20LT-RED',
      'Ship To - Name': 'Bob Griffes',
      'Ship To - Address 1': '1227 S LINCOLN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTOWARES STORE 277',
      'Ship To - Country': 'US',
      'Order - Number': 1346,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Bob Griffes',
      'Ship To - Address 1': '1227 S LINCOLN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTOWARES STORE 277',
      'Ship To - Country': 'US',
      'Order - Number': 1346,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Bob Griffes',
      'Ship To - Address 1': '1227 S LINCOLN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTOWARES STORE 277',
      'Ship To - Country': 'US',
      'Order - Number': 1346,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Carrie Miller',
      'Ship To - Address 1': '1245 CARPENTER AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 381',
      'Ship To - Country': 'US',
      'Order - Number': 1348,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'A1-DG20P-NAVY',
      'Ship To - Name': 'Carrie Miller',
      'Ship To - Address 1': '1245 CARPENTER AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 381',
      'Ship To - Country': 'US',
      'Order - Number': 1348,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Evan Strauss',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 108',
      'Ship To - Country': 'US',
      'Order - Number': 1359,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s Cooling Performance T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'Evan Strauss',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 108',
      'Ship To - Country': 'US',
      'Order - Number': 1359,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55LS-Graphite',
      'Ship To - Name': 'Evan Strauss',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 108',
      'Ship To - Country': 'US',
      'Order - Number': 1359,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Evan Strauss',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 108',
      'Ship To - Country': 'US',
      'Order - Number': 1359,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 4,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Salvatoure Lumetta',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 213',
      'Ship To - Country': 'US',
      'Order - Number': 1360,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20LT-RED',
      'Ship To - Name': 'Salvatoure Lumetta',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 213',
      'Ship To - Country': 'US',
      'Order - Number': 1360,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20W-RED',
      'Ship To - Name': 'Jacki Russell',
      'Ship To - Address 1': '721 E SUMNER ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'BUMPER TO BUMPER HARTFORD',
      'Ship To - Country': 'US',
      'Order - Number': 1361,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20LW-RED',
      'Ship To - Name': 'Jacki Russell',
      'Ship To - Address 1': '721 E SUMNER ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'BUMPER TO BUMPER HARTFORD',
      'Ship To - Country': 'US',
      'Order - Number': 1361,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20L-RED',
      'Ship To - Name': 'Curtis Schulz',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 624',
      'Ship To - Country': 'US',
      'Order - Number': 1363,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Kristi Caine',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 511',
      'Ship To - Country': 'US',
      'Order - Number': 1370,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Nathan Hartman',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 511',
      'Ship To - Country': 'US',
      'Order - Number': 1369,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Karl Rinehart',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 511',
      'Ship To - Country': 'US',
      'Order - Number': 1366,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Edward DeRuiter',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 511',
      'Ship To - Country': 'US',
      'Order - Number': 1364,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20LW-RED',
      'Ship To - Name': 'Anne MacDonald',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 244',
      'Ship To - Country': 'US',
      'Order - Number': 1373,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20P-RED',
      'Ship To - Name': 'Neil McCallum',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 252',
      'Ship To - Country': 'US',
      'Order - Number': 1375,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'James Sterk',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 252',
      'Ship To - Country': 'US',
      'Order - Number': 1374,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20W-RED',
      'Ship To - Name': 'Brenda Culver',
      'Ship To - Address 1': '441 Kirtland SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'Auto Value Lake City 310',
      'Ship To - Country': 'US',
      'Order - Number': 1376,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20W-RED',
      'Ship To - Name': 'Brenda Culver',
      'Ship To - Address 1': '441 Kirtland SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'Auto Value Lake City 310',
      'Ship To - Country': 'US',
      'Order - Number': 1376,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20P-RED',
      'Ship To - Name': 'Francisco Morales',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'BTB 479',
      'Ship To - Country': 'US',
      'Order - Number': 1377,
      'Date - Shipped Date': '5/6/2021 7:00:04 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    }
  ];

  constructor() { }

  ngOnInit(): void {
  }

   // tslint:disable-next-line:typedef
   downloadFile(data: any) {
    const replacer = (key, value) => (value === null ? '' : value); // specify how you want to handle null values here
    const header = Object.keys(data[0]);
    const csv = data.map((row) =>
      header
        .map((fieldName) => JSON.stringify(row[fieldName], replacer))
        .join(',')
    );
    csv.unshift(header.join(','));
    const csvArray = csv.join('\r\n');
    const a = document.createElement('a');
    const blob = new Blob([csvArray], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    a.href = url;
    a.download = 'Shipments-05-06.csv';
    a.click();
    window.URL.revokeObjectURL(url);
    a.remove();
  }

  public removeSlashes(side: string): string {
    if (side) {
      side.replace(/\//g, '');
      return side.replace('<br/>', '');
    }
  }

}
