import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-invoice0417-files',
  templateUrl: './invoice0417-files.component.html',
  styleUrls: ['./invoice0417-files.component.css']
})
export class Invoice0417FilesComponent implements OnInit {

  seventeenData: any =  [
    {
      'Amount - Order Total': 50.75,
      'Item - Name': 'Devon & Jones Men\'s Three-Season Classic Jacket - Large / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 617',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-BTB-L',
      'Ship To - Name': 'Salvatore Ciardo',
      'Ship To - Address 1': '710 CARDINAL LN',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1054,
      'Date - Shipped Date': '4/17/2021 11:06:38 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 50.75
    },
    {
      'Amount - Order Total': 50.75,
      'Item - Name': 'Devon & Jones Men\'s Three-Season Classic Jacket - Large / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 506',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-BTB-L',
      'Ship To - Name': 'Mark Hoeksema',
      'Ship To - Address 1': '3849 OAKES ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1053,
      'Date - Shipped Date': '4/17/2021 11:06:38 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 50.75
    },
    {
      'Amount - Order Total': 126.5,
      'Item - Name': 'Ladies Cooling Performance T-Shirt - 2XL / Graphite',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 12.5,
      'Item - SKU': '403196-NW3201-2XL',
      'Ship To - Name': 'Amanda K. Pohlod',
      'Ship To - Address 1': '6161 CENTER LINE RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1044,
      'Date - Shipped Date': '4/17/2021 11:06:38 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 126.5
    },
    {
      'Amount - Order Total': 49,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - Large / Charcoal',
      'Notes - From Buyer': 'Vassar Automotive\nAttn Rob Loney<br/>Store Number/Name: 657',
      'Item - Qty': 1,
      'Item - Price': 24.5,
      'Item - SKU': '403197-PC90H-AWGC-L',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1057,
      'Date - Shipped Date': '4/17/2021 11:06:38 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 49
    },
    {
      'Amount - Order Total': 49,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - X-Large / Charcoal',
      'Notes - From Buyer': 'Vassar Automotive\nAttn Rob Loney<br/>Store Number/Name: 657',
      'Item - Qty': 1,
      'Item - Price': 24.5,
      'Item - SKU': '403197-PC90H-AWGC-XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1057,
      'Date - Shipped Date': '4/17/2021 11:06:38 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 49
    },
    {
      'Amount - Order Total': 7,
      'Item - Name': 'P&C Core Blend T-Shirt - Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 524',
      'Item - Qty': 1,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-L',
      'Ship To - Name': 'H Durham',
      'Ship To - Address 1': '115 South Market Street',
      'Ship To - Address 2': 'P.O Box 38',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1056,
      'Date - Shipped Date': '4/17/2021 11:06:38 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 7
    },
    {
      'Amount - Order Total': 112.2,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt - Large / Charcoal',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 9.35,
      'Item - SKU': '403199-PC55LS-L',
      'Ship To - Name': 'RON SHEFFIELD',
      'Ship To - Address 1': '2048 N SAINT HELEN RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1037,
      'Date - Shipped Date': '4/17/2021 11:23:07 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 112.2
    },
    {
      'Amount - Order Total': 112.2,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt - Medium / Charcoal',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 9.35,
      'Item - SKU': '403199-PC55LS-M',
      'Ship To - Name': 'RON SHEFFIELD',
      'Ship To - Address 1': '2048 N SAINT HELEN RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1037,
      'Date - Shipped Date': '4/17/2021 11:23:07 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 112.2
    },
    {
      'Amount - Order Total': 112.2,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt - X-Large / Charcoal',
      'Notes - From Buyer': '',
      'Item - Qty': 6,
      'Item - Price': 9.35,
      'Item - SKU': '403199-PC55LS-XL',
      'Ship To - Name': 'RON SHEFFIELD',
      'Ship To - Address 1': '2048 N SAINT HELEN RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1037,
      'Date - Shipped Date': '4/17/2021 11:23:07 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 112.2
    },
    {
      'Amount - Order Total': 52.85,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt - X-Large / Charcoal',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 9.35,
      'Item - SKU': '403199-PC55LS-XL',
      'Ship To - Name': 'John Oates',
      'Ship To - Address 1': '500 N PONTIAC TRL',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1035,
      'Date - Shipped Date': '4/17/2021 11:23:07 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 52.85
    },
    {
      'Amount - Order Total': 31,
      'Item - Name': 'P&C Essential Fleece Crewneck Sweatshirt - Large / Charcoal',
      'Notes - From Buyer': 'Holly Stansbury AV Charlevoix\n1087<br/>Store Number/Name: 1087',
      'Item - Qty': 2,
      'Item - Price': 15.5,
      'Item - SKU': '403200-PC90-L',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1049,
      'Date - Shipped Date': '4/17/2021 11:06:38 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 31
    },
    {
      'Amount - Order Total': 52.85,
      'Item - Name': 'Port Authority® Core Soft Shell Jacket - Medium / Black',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 43.5,
      'Item - SKU': '403203-J317-AV-M',
      'Ship To - Name': 'John Oates',
      'Ship To - Address 1': '500 N PONTIAC TRL',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1035,
      'Date - Shipped Date': '4/17/2021 11:23:07 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 52.85
    },
    {
      'Amount - Order Total': 43.5,
      'Item - Name': 'Port Authority® Ladies Core Soft Shell Jacket - Large / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 544',
      'Item - Qty': 1,
      'Item - Price': 43.5,
      'Item - SKU': '403239-L317-MAXI-L',
      'Ship To - Name': 'Lindsey OCallaghan',
      'Ship To - Address 1': '3109 MADISON AVE SE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1059,
      'Date - Shipped Date': '4/17/2021 11:06:38 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 43.5
    },
    {
      'Amount - Order Total': 90,
      'Item - Name': 'Devon & Jones CrownLux Performance™ Men\'s Clubhouse Micro-Stripe Quarter-Zip - Medium / Black',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 47.5,
      'Item - SKU': '403246-DG480-M',
      'Ship To - Name': 'Bruce Gumenick',
      'Ship To - Address 1': '3980 LAKE FRONT ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1045,
      'Date - Shipped Date': '4/17/2021 11:23:07 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 90
    },
    {
      'Amount - Order Total': 90,
      'Item - Name': 'Devon & Jones CrownLux Performance™ Men\'s Tonal Mini Check Shirt - Medium / Navy',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 42.5,
      'Item - SKU': '403248-DG535-M',
      'Ship To - Name': 'Bruce Gumenick',
      'Ship To - Address 1': '3980 LAKE FRONT ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1045,
      'Date - Shipped Date': '4/17/2021 11:23:07 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 90
    },
    {
      'Amount - Order Total': 126.5,
      'Item - Name': 'Devon & Jones Ladies\' CrownLux Performance™ Stretch Tunic - 2XL / Navy',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 44.5,
      'Item - SKU': '403249-DG542W-2X',
      'Ship To - Name': 'Amanda K. Pohlod',
      'Ship To - Address 1': '6161 CENTER LINE RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1044,
      'Date - Shipped Date': '4/17/2021 11:06:38 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 126.5
    },
    {
      'Amount - Order Total': 126.5,
      'Item - Name': 'Women\'s Windsor Henley - 2XL / Grey/White Stripe',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 34.5,
      'Item - SKU': '403250-2913-2X',
      'Ship To - Name': 'Amanda K. Pohlod',
      'Ship To - Address 1': '6161 CENTER LINE RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1044,
      'Date - Shipped Date': '4/17/2021 11:06:38 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 126.5
    },
    {
      'Amount - Order Total': 71,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - Large / Navy',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 35.5,
      'Item - SKU': '403272-DG20P-A1-L',
      'Ship To - Name': 'Jerry Bruins',
      'Ship To - Address 1': '963 WASHINGTON AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1043,
      'Date - Shipped Date': '4/17/2021 11:06:38 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 71
    },
    {
      'Amount - Order Total': 126.5,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo - 2XL / Red',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 35,
      'Item - SKU': '403275-DG20W-AV-2XL',
      'Ship To - Name': 'Amanda K. Pohlod',
      'Ship To - Address 1': '6161 CENTER LINE RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1044,
      'Date - Shipped Date': '4/17/2021 11:06:38 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 126.5
    },
    {
      'Amount - Order Total': 52.75,
      'Item - Name': 'Devon & Jones Ladies Three-Season Classic Jacket - 2XL / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 511',
      'Item - Qty': 1,
      'Item - Price': 52.75,
      'Item - SKU': '403277-D700W-AVPS-2X',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1058,
      'Date - Shipped Date': '4/17/2021 11:06:38 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 52.75
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'A1-DG20P-NAVY',
      'Ship To - Name': 'Lester Modrow',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 180',
      'Ship To - Country': 'US',
      'Order - Number': 1228,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'A1-DG20P-NAVY',
      'Ship To - Name': 'Chris Bates',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 180',
      'Ship To - Country': 'US',
      'Order - Number': 1227,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'Scott Zurawski',
      'Ship To - Address 1': '97 S MICHIGAN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 290',
      'Ship To - Country': 'US',
      'Order - Number': 1209,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'John Doan',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 517',
      'Ship To - Country': 'US',
      'Order - Number': 1189,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'John Oates',
      'Ship To - Address 1': '500 n pontiactr',
      'Ship To - Address 2': 286,
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 327',
      'Ship To - Country': 'US',
      'Order - Number': 1274,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'Douglas Sirls',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 327',
      'Ship To - Country': 'US',
      'Order - Number': 1273,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20LW-RED',
      'Ship To - Name': 'Wendy Smigielski',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 361',
      'Ship To - Country': 'US',
      'Order - Number': 1322,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'James North',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 525',
      'Ship To - Country': 'US',
      'Order - Number': 1223,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Katie Prieur',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 286',
      'Ship To - Country': 'US',
      'Order - Number': 1267,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Michael Kroll',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 345',
      'Ship To - Country': 'US',
      'Order - Number': 1290,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 4,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Jordan Lafountain',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 367',
      'Ship To - Country': 'US',
      'Order - Number': 1287,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'brenda hudgen',
      'Ship To - Address 1': '317 W PROSPECT ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'PERFORMANCE AUTOVALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1291,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Joseph Walton',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 290',
      'Ship To - Country': 'US',
      'Order - Number': 1296,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Samuel Bowerman',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 243',
      'Ship To - Country': 'US',
      'Order - Number': 1298,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Samuel Bowerman',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 243',
      'Ship To - Country': 'US',
      'Order - Number': 1298,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Samuel Bowerman',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 243',
      'Ship To - Country': 'US',
      'Order - Number': 1298,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Douglas Roberts',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 349',
      'Ship To - Country': 'US',
      'Order - Number': 1307,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Angela Canfield',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 361',
      'Ship To - Country': 'US',
      'Order - Number': 1315,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Roger Smith',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 361',
      'Ship To - Country': 'US',
      'Order - Number': 1314,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Robert Crampton',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 361',
      'Ship To - Country': 'US',
      'Order - Number': 1313,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Nicholas Mungia',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 256',
      'Ship To - Country': 'US',
      'Order - Number': 1309,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Wendy Smigielski',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 361',
      'Ship To - Country': 'US',
      'Order - Number': 1322,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'James Leffew',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 361',
      'Ship To - Country': 'US',
      'Order - Number': 1321,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Wade King',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 225',
      'Ship To - Country': 'US',
      'Order - Number': 1319,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Robert Stone',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 361',
      'Ship To - Country': 'US',
      'Order - Number': 1333,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Tyler Stone',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV361-JACKSON',
      'Ship To - Country': 'US',
      'Order - Number': 1332,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'James Pearson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 180',
      'Ship To - Country': 'US',
      'Order - Number': 1230,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Thomas Smith',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 180',
      'Ship To - Country': 'US',
      'Order - Number': 1229,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'McKenzie Avery',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 525',
      'Ship To - Country': 'US',
      'Order - Number': 1221,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Michael Magda',
      'Ship To - Address 1': '97 S MICHIGAN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 290',
      'Ship To - Country': 'US',
      'Order - Number': 1211,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Richard Klein',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 327',
      'Ship To - Country': 'US',
      'Order - Number': 1208,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'William Kinney',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 358',
      'Ship To - Country': 'US',
      'Order - Number': 1207,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Scott Rapelje',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 245',
      'Ship To - Country': 'US',
      'Order - Number': 1194,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Leslie Frazier',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 517',
      'Ship To - Country': 'US',
      'Order - Number': 1192,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Jack Baker',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 286',
      'Ship To - Country': 'US',
      'Order - Number': 1269,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Louis Prieur',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 286',
      'Ship To - Country': 'US',
      'Order - Number': 1268,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'David Husted',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 215',
      'Ship To - Country': 'US',
      'Order - Number': 1271,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Scott Rapelje',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 245',
      'Ship To - Country': 'US',
      'Order - Number': 1272,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Anthony Guglielmotti',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 327',
      'Ship To - Country': 'US',
      'Order - Number': 1275,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Jack Ellison',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 270',
      'Ship To - Country': 'US',
      'Order - Number': 1295,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Gordon Harris',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 270',
      'Ship To - Country': 'US',
      'Order - Number': 1294,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Matthew Burns',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 270',
      'Ship To - Country': 'US',
      'Order - Number': 1293,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Evan Davis',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 270',
      'Ship To - Country': 'US',
      'Order - Number': 1297,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Dustin Huggins',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 227',
      'Ship To - Country': 'US',
      'Order - Number': 1299,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Samuel Bowerman',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 243',
      'Ship To - Country': 'US',
      'Order - Number': 1298,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Bradley Kamaloski',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 256',
      'Ship To - Country': 'US',
      'Order - Number': 1308,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Michael Barton',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 361',
      'Ship To - Country': 'US',
      'Order - Number': 1316,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Deborah Loszewski',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 285',
      'Ship To - Country': 'US',
      'Order - Number': 1216,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Justin Cook',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 267',
      'Ship To - Country': 'US',
      'Order - Number': 1195,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Jason Owens',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 517',
      'Ship To - Country': 'US',
      'Order - Number': 1188,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'John Brainerd',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 255',
      'Ship To - Country': 'US',
      'Order - Number': 1200,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Gregory Diorka',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 286',
      'Ship To - Country': 'US',
      'Order - Number': 1270,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Jeremy Braun',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 367',
      'Ship To - Country': 'US',
      'Order - Number': 1288,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'George Gaskins',
      'Ship To - Address 1': '3438 LINCOLN RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1292,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Jeffery Coffman',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 320',
      'Ship To - Country': 'US',
      'Order - Number': 1302,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Bobby Rudd',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 320',
      'Ship To - Country': 'US',
      'Order - Number': 1301,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20W-RED',
      'Ship To - Name': 'Wendy Smigielski',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 361',
      'Ship To - Country': 'US',
      'Order - Number': 1322,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20W-RED',
      'Ship To - Name': 'Laura Stanley',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 310',
      'Ship To - Country': 'US',
      'Order - Number': 1279,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20W-RED',
      'Ship To - Name': 'April Leffew',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 367',
      'Ship To - Country': 'US',
      'Order - Number': 1289,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s Cooling Performance T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AutoWaresGroup-N3142-Graphite',
      'Ship To - Name': 'Isaac Thomas',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1205,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s Cooling Performance T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AutoWaresGroup-N3142-Graphite',
      'Ship To - Name': 'Gary Moore',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1206,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s Cooling Performance T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AutoWaresGroup-N3142-Graphite',
      'Ship To - Name': 'Regina Townsend',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1203,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies Cooling Performance T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AutoWaresGroup-NW3201-Graphite',
      'Ship To - Name': 'Mark Stanton',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 254',
      'Ship To - Country': 'US',
      'Order - Number': 1212,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Lawrence McNamara',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO-WARES',
      'Ship To - Country': 'US',
      'Order - Number': 1329,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Willaim Wind',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO-WARES',
      'Ship To - Country': 'US',
      'Order - Number': 1328,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AutoWaresGroup-PC55-Graphite',
      'Ship To - Name': 'William Leininger',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 525',
      'Ship To - Country': 'US',
      'Order - Number': 1224,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Michael Jones',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1278,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Michael Cupples',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1277,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'William Morrison',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1276,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AutoWaresGroup-PC55LS-Graphite',
      'Ship To - Name': 'Patricia Bojko',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1202,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Crewneck Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AutoWaresGroup-PC90-Charcoal',
      'Ship To - Name': 'Tim Brewer',
      'Ship To - Address 1': '4333 ROBERTSON RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 610',
      'Ship To - Country': 'US',
      'Order - Number': 1201,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AutoWaresGroup-PC90H-Graphite',
      'Ship To - Name': 'Terry Baker',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 525',
      'Ship To - Country': 'US',
      'Order - Number': 1222,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20L-RED',
      'Ship To - Name': 'Emmanuel Goodwin',
      'Ship To - Address 1': '517 S CARLTON AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'BUMPER TO BUMPER WHEATON',
      'Ship To - Country': 'US',
      'Order - Number': 1310,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20L-RED',
      'Ship To - Name': 'Emmanuel Goodwin',
      'Ship To - Address 1': '517 S CARLTON AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'BUMPER TO BUMPER WHEATON',
      'Ship To - Country': 'US',
      'Order - Number': 1310,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20P-RED',
      'Ship To - Name': 'Brian Patten',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 298',
      'Ship To - Country': 'US',
      'Order - Number': 1186,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20P-RED',
      'Ship To - Name': 'Emmanuel Goodwin',
      'Ship To - Address 1': '517 S CARLTON AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'BUMPER TO BUMPER WHEATON',
      'Ship To - Country': 'US',
      'Order - Number': 1310,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20P-RED',
      'Ship To - Name': 'Max Alber',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 623',
      'Ship To - Country': 'US',
      'Order - Number': 1327,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20P-RED',
      'Ship To - Name': 'William Heisler',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 662',
      'Ship To - Country': 'US',
      'Order - Number': 1220,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20T-RED',
      'Ship To - Name': 'Hunter Watzlawick',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 620',
      'Ship To - Country': 'US',
      'Order - Number': 1311,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'MAXI-DG20P-RED',
      'Ship To - Name': 'Bruce Bartz',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 544',
      'Ship To - Country': 'US',
      'Order - Number': 1219,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'MAXI-DG20P-RED',
      'Ship To - Name': 'Robert Roberts',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 544',
      'Ship To - Country': 'US',
      'Order - Number': 1218,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'MAXI-DG20P-RED',
      'Ship To - Name': 'Daniel Urbanowski',
      'Ship To - Address 1': '3109 MADISON AVE SE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 544',
      'Ship To - Country': 'US',
      'Order - Number': 1280,
      'Date - Shipped Date': '4/17/2021 11:13:35 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'MAXI-DG20P-RED',
      'Ship To - Name': 'Larry Griffin',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 544',
      'Ship To - Country': 'US',
      'Order - Number': 1231,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'MAXI-DG20P-RED',
      'Ship To - Name': 'Dean Lounsbery',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 544',
      'Ship To - Country': 'US',
      'Order - Number': 1217,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'MAXI-DG20P-RED',
      'Ship To - Name': 'Corey Carney',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 544',
      'Ship To - Country': 'US',
      'Order - Number': 1215,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'MAXI-DG20T-RED',
      'Ship To - Name': 'Steven Sheldon',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 544',
      'Ship To - Country': 'US',
      'Order - Number': 1232,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'MAXI-DG20T-RED',
      'Ship To - Name': 'Jason Harper',
      'Ship To - Address 1': '7819 KENSINGTON RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 549',
      'Ship To - Country': 'US',
      'Order - Number': 1193,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'MAXI-DG20T-RED',
      'Ship To - Name': 'Dale Henry',
      'Ship To - Address 1': '7819 KENSINGTON RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 549',
      'Ship To - Country': 'US',
      'Order - Number': 1191,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'MAXI-DG20T-RED',
      'Ship To - Name': 'Jacques Mosier',
      'Ship To - Address 1': '7819 KENSINGTON RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 549',
      'Ship To - Country': 'US',
      'Order - Number': 1190,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'MAXI-DG20W-RED',
      'Ship To - Name': 'Coleene Clark-Kellar',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 544',
      'Ship To - Country': 'US',
      'Order - Number': 1214,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'MAXI-DG20W-RED',
      'Ship To - Name': 'Evelyn Westervelt',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 544',
      'Ship To - Country': 'US',
      'Order - Number': 1213,
      'Date - Shipped Date': '4/17/2021 11:26:23 AM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0
    }
  ];

  test: any = [{
    Id: 1,
    Order: '1038',
    // tslint:disable-next-line:quotemark
    Item: "Devon & Jones CrownLux Performance™ Ladies' Clubhouse Micro-Stripe Quarter-Zip - X-Large / Black",
    Employee: 'Lindsey OCallaghan',
    Location: 'GRAND RAPIDS',
    ShipDate: '04-12-21',
    Source: 'Auto-Wares Shopify',
    Quantity: 1,
    Price: 47.50,
  }];

  constructor() { }

  ngOnInit(): void {
    console.log(this.seventeenData);
  }


  // tslint:disable-next-line:typedef
  downloadFile(data: any) {
    const replacer = (key, value) => (value === null ? '' : value); // specify how you want to handle null values here
    const header = Object.keys(data[0]);
    const csv = data.map((row) =>
      header
        .map((fieldName) => JSON.stringify(row[fieldName], replacer))
        .join(',')
    );
    csv.unshift(header.join(','));
    const csvArray = csv.join('\r\n');
    const a = document.createElement('a');
    const blob = new Blob([csvArray], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    a.href = url;
    a.download = 'Shipments-04-17.csv';
    a.click();
    window.URL.revokeObjectURL(url);
    a.remove();
  }

  public removeSlashes(side: string): string {
    if (side) {
      side.replace(/\//g, '');
      return side.replace('<br/>', '');
    }
  }

}
