import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-invoice0605',
  templateUrl: './invoice0605.component.html',
  styleUrls: ['./invoice0605.component.css'],
})
export class Invoice0605Component implements OnInit {
  sixfive: any = [
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20W-RED',
      'Ship To - Name': 'Stacia Kooistra',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 279',
      'Ship To - Country': 'US',
      'Order - Number': 1458,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Austin Dordon',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 279',
      'Ship To - Country': 'US',
      'Order - Number': 1457,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Nathaniel Mitchell',
      'Ship To - Address 1': '226 W SUPERIOR ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1453,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20P-RED',
      'Ship To - Name': 'Kendra Westphal',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 634',
      'Ship To - Country': 'US',
      'Order - Number': 1452,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20W-RED',
      'Ship To - Name': 'Nancy Johnston',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'BUMPER TO BUMPER AURORA 431',
      'Ship To - Country': 'US',
      'Order - Number': 1450,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55LS-Graphite',
      'Ship To - Name': 'Stacey Ledesma',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 102',
      'Ship To - Country': 'US',
      'Order - Number': 1446,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Small, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Stacey Ledesma',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 102',
      'Ship To - Country': 'US',
      'Order - Number': 1446,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Small, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Thomas Romine',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 102',
      'Ship To - Country': 'US',
      'Order - Number': 1445,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Erick Buitron',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 101',
      'Ship To - Country': 'US',
      'Order - Number': 1442,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Mark Miller',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 101',
      'Ship To - Country': 'US',
      'Order - Number': 1441,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Tyler Michels',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 267',
      'Ship To - Country': 'US',
      'Order - Number': 1439,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 4XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Tall Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'robert Flores',
      'Ship To - Address 1': 'STORE 267',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1438,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XT, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Tall Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Justin Cook',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 267',
      'Ship To - Country': 'US',
      'Order - Number': 1437,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XT, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Joshua Stutesman',
      'Ship To - Address 1': '1904 M 139',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE BENTON HARBOR',
      'Ship To - Country': 'US',
      'Order - Number': 1436,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Tall Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Johnathon Reiffers',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 215',
      'Ship To - Country': 'US',
      'Order - Number': 1435,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: LT, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Tall Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Micah Wann',
      'Ship To - Address 1': '14964 CLEVELAND ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES',
      'Ship To - Country': 'US',
      'Order - Number': 1434,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: LT, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 4,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20W-RED',
      'Ship To - Name': 'Jacki Russell',
      'Ship To - Address 1': '721 E SUMNER ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'BUMPER TO BUMPER HARTFORD',
      'Ship To - Country': 'US',
      'Order - Number': 1418,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Michael Labo',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 286',
      'Ship To - Country': 'US',
      'Order - Number': 1414,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 5XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's Cooling Performance T-Shirt",
      'Notes - From Buyer': '1st shift',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'Casey Placencia',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1411,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Graphite',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '1st shift',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Casey Placencia',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1411,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 4,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Natasha Bristol',
      'Ship To - Address 1': '1227 S LINCOLN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV277',
      'Ship To - Country': 'US',
      'Order - Number': 1410,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Long Sleeve Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'Natasha Bristol',
      'Ship To - Address 1': '1227 S LINCOLN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV277',
      'Ship To - Country': 'US',
      'Order - Number': 1410,
      'Date - Shipped Date': '6/5/2021 7:22:03 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red',
    },
    {
      'Amount - Order Total': 50.75,
      'Item - Name':
        'Devon & Jones Ladies Three-Season Classic Jacket - X-Large / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 381',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403277-D700W-AVPS-XL',
      'Ship To - Name': 'Carrie Miller',
      'Ship To - Address 1': '1245 CARPENTER AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV IRON MTN',
      'Ship To - Country': 'US',
      'Order - Number': 1111,
      'Date - Shipped Date': '6/5/2021 7:17:09 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 50.75,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 85,
      'Item - Name':
        "Men's CrownLux Performance Plaited Tall Long Sleeve Polo - XLT / Red",
      'Notes - From Buyer': '<br/>Store Number/Name: 277',
      'Item - Qty': 1,
      'Item - Price': 41.5,
      'Item - SKU': '403274-DG20LT-AVPS-XLT',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1108,
      'Date - Shipped Date': '6/5/2021 7:17:09 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 85,
      'Item - Fill SKU': '',
      'Item - Options': 'Right Sleeve Co-Op: Walker',
    },
    {
      'Amount - Order Total': 85,
      'Item - Name':
        "Men's CrownLux Performance Plaited Tall Long Sleeve Polo - 3XT / Red",
      'Notes - From Buyer': '<br/>Store Number/Name: 277',
      'Item - Qty': 1,
      'Item - Price': 43.5,
      'Item - SKU': '403274-DG20LT-AVPS-3XT',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1108,
      'Date - Shipped Date': '6/5/2021 7:17:09 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 85,
      'Item - Fill SKU': '',
      'Item - Options': 'Right Sleeve Co-Op: Walker',
    },
    {
      'Amount - Order Total': 106.5,
      'Item - Name':
        "Men's CrownLux Performance Plaited Polo with Pocket - Large / Red",
      'Notes - From Buyer': '<br/>Store Number/Name: 244',
      'Item - Qty': 1,
      'Item - Price': 35.5,
      'Item - SKU': '403272-DG20P-AVPS-L',
      'Ship To - Name': 'Dell Bartello',
      'Ship To - Address 1': '1569 WILLOUGHBY RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1107,
      'Date - Shipped Date': '6/5/2021 7:17:09 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 106.5,
      'Item - Fill SKU': '',
      'Item - Options': 'Right Sleeve Co-Op: Walker',
    },
    {
      'Amount - Order Total': 106.5,
      'Item - Name':
        "Men's CrownLux Performance Plaited Polo with Pocket - Large / Red",
      'Notes - From Buyer': '<br/>Store Number/Name: 244',
      'Item - Qty': 2,
      'Item - Price': 35.5,
      'Item - SKU': '403272-DG20P-BTB-L',
      'Ship To - Name': 'Dell Bartello',
      'Ship To - Address 1': '1569 WILLOUGHBY RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1107,
      'Date - Shipped Date': '6/5/2021 7:17:09 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 106.5,
      'Item - Fill SKU': '',
      'Item - Options': 'Right Sleeve Co-Op: Walker',
    },
    {
      'Amount - Order Total': 7,
      'Item - Name': 'P&C Core Blend T-Shirt - X-Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 453',
      'Item - Qty': 1,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-XL',
      'Ship To - Name': 'Chris Rohder',
      'Ship To - Address 1': '4980 PARK LAKE RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1106,
      'Date - Shipped Date': '6/5/2021 7:17:09 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 7,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 59.5,
      'Item - Name':
        'P&C Essential Fleece Pullover Hooded Sweatshirt - Medium / Charcoal',
      'Notes - From Buyer': 'James Irwin<br/>Store Number/Name: 870',
      'Item - Qty': 1,
      'Item - Price': 24.5,
      'Item - SKU': '403197-PC90H-AWGC-M',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1105,
      'Date - Shipped Date': '6/5/2021 7:17:09 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 59.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 59.5,
      'Item - Name': 'P&C Core Blend T-Shirt - Medium / Charcoal',
      'Notes - From Buyer': 'James Irwin<br/>Store Number/Name: 870',
      'Item - Qty': 5,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-M',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1105,
      'Date - Shipped Date': '6/5/2021 7:17:09 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 59.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 44.5,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt - 2XL / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 362',
      'Item - Qty': 1,
      'Item - Price': 12.5,
      'Item - SKU': '403199-PC55LS-AWGC-2X',
      'Ship To - Name': 'Brenda Hudgen',
      'Ship To - Address 1': '317 W PROSPECT ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'PREFORMANCE SOUTH',
      'Ship To - Country': 'US',
      'Order - Number': 1104,
      'Date - Shipped Date': '6/5/2021 7:17:09 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 44.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 44.5,
      'Item - Name': "Men's Cooling Performance T-Shirt - 2XL / Graphite",
      'Notes - From Buyer': '<br/>Store Number/Name: 362',
      'Item - Qty': 1,
      'Item - Price': 12.5,
      'Item - SKU': '403201-N3142-AWGC-2XL',
      'Ship To - Name': 'Brenda Hudgen',
      'Ship To - Address 1': '317 W PROSPECT ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'PREFORMANCE SOUTH',
      'Ship To - Country': 'US',
      'Order - Number': 1104,
      'Date - Shipped Date': '6/5/2021 7:17:09 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 44.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 44.5,
      'Item - Name': 'P&C Core Blend T-Shirt - 2XL / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 362',
      'Item - Qty': 2,
      'Item - Price': 9.75,
      'Item - SKU': '403198-PC55-AWGC-2X',
      'Ship To - Name': 'Brenda Hudgen',
      'Ship To - Address 1': '317 W PROSPECT ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'PREFORMANCE SOUTH',
      'Ship To - Country': 'US',
      'Order - Number': 1104,
      'Date - Shipped Date': '6/5/2021 7:17:09 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 44.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 50.75,
      'Item - Name':
        'Devon & Jones Ladies Three-Season Classic Jacket - Medium / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 283',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403277-D700W-AVPS-M',
      'Ship To - Name': 'Kylene Maviglia',
      'Ship To - Address 1': '11625 N SAGINAW ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV MT MORRIS',
      'Ship To - Country': 'US',
      'Order - Number': 1099,
      'Date - Shipped Date': '6/5/2021 7:17:09 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 50.75,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
  ];

  constructor() {}

  ngOnInit(): void {}
  // tslint:disable-next-line:typedef
  downloadFile(data: any) {
    const replacer = (key, value) => (value === null ? '' : value); // specify how you want to handle null values here
    const header = Object.keys(data[0]);
    const csv = data.map((row) =>
      header
        .map((fieldName) => JSON.stringify(row[fieldName], replacer))
        .join(',')
    );
    csv.unshift(header.join(','));
    const csvArray = csv.join('\r\n');
    const a = document.createElement('a');
    const blob = new Blob([csvArray], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    a.href = url;
    a.download = 'Shipments-06-05.csv';
    a.click();
    window.URL.revokeObjectURL(url);
    a.remove();
  }

  public removeSlashes(side: string): string {
    if (side) {
      side.replace(/\//g, '');
      return side.replace('<br/>', '');
    }
  }
}
