import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-invoice0701',
  templateUrl: './invoice0701.component.html',
  styleUrls: ['./invoice0701.component.css'],
})
export class Invoice0701Component implements OnInit {
  julone: any = [
    {
      'Amount - Order Total': 170,
      'Item - Name':
        'Ladies CrownLux Performance Plaited Long Sleeve Polo - Medium / Red',
      'Notes - From Buyer': '<br/>Store Number/Name: 56 (AV 243)',
      'Item - Qty': 2,
      'Item - Price': 35.5,
      'Item - SKU': '403276-DG20LW-AVPS-M',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1117,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 170,
      'Item - Fill SKU': '',
      'Item - Options': 'Right Sleeve Co-Op: Gates',
    },
    {
      'Amount - Order Total': 170,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo - Medium / Red',
      'Notes - From Buyer': '<br/>Store Number/Name: 56 (AV 243)',
      'Item - Qty': 3,
      'Item - Price': 33,
      'Item - SKU': '403275-DG20W-AVPS-M',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1117,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 170,
      'Item - Fill SKU': '',
      'Item - Options': 'Right Sleeve Co-Op: Gates',
    },
    {
      'Amount - Order Total': 50.75,
      'Item - Name':
        "Devon & Jones Men's Three-Season Classic Jacket - X-Large / Black",
      'Notes - From Buyer': '<br/>Store Number/Name: 259',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-AVPS-XL',
      'Ship To - Name': 'Cody Cole',
      'Ship To - Address 1': '1789 S OTSEGO AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV GAYLORD',
      'Ship To - Country': 'US',
      'Order - Number': 1119,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 50.75,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 52.75,
      'Item - Name':
        "Devon & Jones Men's Three-Season Classic Jacket - 2XL / Black",
      'Notes - From Buyer': '<br/>Store Number/Name: 521',
      'Item - Qty': 1,
      'Item - Price': 52.75,
      'Item - SKU': '403195-D700-AVPS-2X',
      'Ship To - Name': 'Ronald  Coats',
      'Ship To - Address 1': '6229 CROSS CREEK BLVD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV FORT WAYNE',
      'Ship To - Country': 'US',
      'Order - Number': 1118,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 52.75,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 45.5,
      'Item - Name':
        'Port Authority® Core Soft Shell Jacket - 2XL / Black / Auto-Wares Group of Companies',
      'Notes - From Buyer': '<br/>Store Number/Name: 70',
      'Item - Qty': 1,
      'Item - Price': 45.5,
      'Item - SKU': '403203-J317-AWGC-2X',
      'Ship To - Name': 'Aaron Wisniewski',
      'Ship To - Address 1': '3342 GLASGOW DR',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1125,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 45.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 42.5,
      'Item - Name':
        "Devon & Jones CrownLux Performance™ Men's Tonal Mini Check Shirt - Large / Navy / Auto-Wares Group of Companies",
      'Notes - From Buyer': '<br/>Store Number/Name: 325',
      'Item - Qty': 1,
      'Item - Price': 42.5,
      'Item - SKU': '403248-DG535-AWGC-L',
      'Ship To - Name': 'Jeff Stucki',
      'Ship To - Address 1': '18675 SUMPTER RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1124,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 42.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 71,
      'Item - Name':
        "Men's CrownLux Performance Plaited Polo with Pocket - Large / Red",
      'Notes - From Buyer': '<br/>Store Number/Name: 325',
      'Item - Qty': 2,
      'Item - Price': 35.5,
      'Item - SKU': '403272-DG20P-AVPS-L',
      'Ship To - Name': 'Jeff Stucki',
      'Ship To - Address 1': '18675 SUMPTER RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1123,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 71,
      'Item - Fill SKU': '',
      'Item - Options': 'Right Sleeve Co-Op: Gates',
    },
    {
      'Amount - Order Total': 45.5,
      'Item - Name': 'Port Authority® Core Soft Shell Jacket - 3XL / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 662',
      'Item - Qty': 1,
      'Item - Price': 45.5,
      'Item - SKU': '403203-J317-SG-3X',
      'Ship To - Name': 'Tim Frank',
      'Ship To - Address 1': '152 ANDREA AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTOWARES',
      'Ship To - Country': 'US',
      'Order - Number': 1122,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 45.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 70,
      'Item - Name':
        "North End Men's Flux Mélange Bonded Fleece Jacket - Medium / Carbon/Oly Red / Auto-Wares Group of Companies",
      'Notes - From Buyer': '<br/>Store Number/Name: 358',
      'Item - Qty': 1,
      'Item - Price': 70,
      'Item - SKU': '403244-88697-AWGC-M',
      'Ship To - Name': 'Brad Ralls',
      'Ship To - Address 1': '14255 KNOLSON ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1126,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 70,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 84,
      'Item - Name':
        'Port Authority® Value Fleece Jacket - 2XL / True Red / Auto-Wares Group of Companies',
      'Notes - From Buyer': '<br/>Store Number/Name: 542',
      'Item - Qty': 1,
      'Item - Price': 37.5,
      'Item - SKU': '403242-F217-AWGC-2X',
      'Ship To - Name': 'Hans E Hellenberg',
      'Ship To - Address 1': '5916 2 MILE RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'MAXI AUTOMOTIVE SUPPLY',
      'Ship To - Country': 'US',
      'Order - Number': 1129,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 84,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 84,
      'Item - Name':
        'Port Authority ® Sweater Fleece Vest - 2XL / Grey Heather / Auto-Wares Group of Companies',
      'Notes - From Buyer': '<br/>Store Number/Name: 542',
      'Item - Qty': 1,
      'Item - Price': 46.5,
      'Item - SKU': '403236-F236-AWGC-2X',
      'Ship To - Name': 'Hans E Hellenberg',
      'Ship To - Address 1': '5916 2 MILE RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'MAXI AUTOMOTIVE SUPPLY',
      'Ship To - Country': 'US',
      'Order - Number': 1129,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 84,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 31.5,
      'Item - Name':
        'P&C Essential Fleece Pullover Hooded Sweatshirt - 2XL / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 619',
      'Item - Qty': 1,
      'Item - Price': 31.5,
      'Item - SKU': '403197-PC90H-AWGC-2X',
      'Ship To - Name': 'Joanne Yuma',
      'Ship To - Address 1': '3435 GALLAGHER RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'BUMPER TO BUMPER',
      'Ship To - Country': 'US',
      'Order - Number': 1131,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 31.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 50.75,
      'Item - Name':
        "Devon & Jones Men's Three-Season Classic Jacket - Large / Black",
      'Notes - From Buyer': '<br/>Store Number/Name: 612',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-BTB-L',
      'Ship To - Name': 'Rick Parks',
      'Ship To - Address 1': '6982 HERON WAY',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1133,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 50.75,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 44.5,
      'Item - Name':
        "Devon & Jones CrownLux Performance™ Men's Tonal Mini Check Shirt - 2XL / Navy / Auto Value Parts Stores",
      'Notes - From Buyer': '<br/>Store Number/Name: 573',
      'Item - Qty': 1,
      'Item - Price': 44.5,
      'Item - SKU': '403248-DG535-AVPS-2X',
      'Ship To - Name': 'Mike Stephens',
      'Ship To - Address 1': '337 N MAIN ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'QUALITY AUTO PARTS',
      'Ship To - Country': 'US',
      'Order - Number': 1134,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 44.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 92,
      'Item - Name': 'P&C Core Blend T-Shirt - 4XL / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 346',
      'Item - Qty': 4,
      'Item - Price': 10.25,
      'Item - SKU': '403198-PC55-AWGC-4X',
      'Ship To - Name': 'Jon Nardi',
      'Ship To - Address 1': '11935 US HIGHWAY 23 S',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1136,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 92,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 92,
      'Item - Name': 'P&C Core Blend T-Shirt - 5XL / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 346',
      'Item - Qty': 4,
      'Item - Price': 11,
      'Item - SKU': '403198-PC55-AWGC-5X',
      'Ship To - Name': 'Jon Nardi',
      'Ship To - Address 1': '11935 US HIGHWAY 23 S',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1136,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 92,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 92,
      'Item - Name': 'P&C Core Blend T-Shirt - Small / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 346',
      'Item - Qty': 1,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-S',
      'Ship To - Name': 'Jon Nardi',
      'Ship To - Address 1': '11935 US HIGHWAY 23 S',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1136,
      'Date - Shipped Date': '7/1/2021 7:52:25 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 92,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 4,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'S & G AUTO VALUE',
      'Ship To - Address 1': '3350 W LIBERTY RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1494,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Long Sleeve Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'S & G AUTO VALUE',
      'Ship To - Address 1': '3350 W LIBERTY RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1494,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20W-RED',
      'Ship To - Name': 'James Collins',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 361',
      'Ship To - Country': 'US',
      'Order - Number': 1497,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 4XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Jason Owens',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 517',
      'Ship To - Country': 'US',
      'Order - Number': 1518,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Katherine Montgomery',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 213',
      'Ship To - Country': 'US',
      'Order - Number': 1521,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Michael Woodham',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 213',
      'Ship To - Country': 'US',
      'Order - Number': 1520,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20W-RED',
      'Ship To - Name': 'Darlene Renaud',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 213',
      'Ship To - Country': 'US',
      'Order - Number': 1519,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'andy leslie',
      'Ship To - Address 1': '3270 MAIN ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1556,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'James Sterk',
      'Ship To - Address 1': '1140 S LAPEER RD # 2764',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 252,
      'Ship To - Country': 'US',
      'Order - Number': 1558,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 4XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Tall Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 4,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Roger Haveman',
      'Ship To - Address 1': '2665 84TH ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE #507',
      'Ship To - Country': 'US',
      'Order - Number': 1561,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: XLT, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Tall Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Alejandro Alba',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 507',
      'Ship To - Country': 'US',
      'Order - Number': 1560,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: XLT, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Long Sleeve Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'Robert Gardner',
      'Ship To - Address 1': '4980 PARK LAKE RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 453',
      'Ship To - Country': 'US',
      'Order - Number': 1562,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's Cooling Performance T-Shirt",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'David Vorpe',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 102',
      'Ship To - Country': 'US',
      'Order - Number': 1565,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Small, Color: Graphite',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's Cooling Performance T-Shirt",
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'Lawson Tell',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 102',
      'Ship To - Country': 'US',
      'Order - Number': 1566,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Graphite',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Lawson Tell',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 102',
      'Ship To - Country': 'US',
      'Order - Number': 1566,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55LS-Graphite',
      'Ship To - Name': 'Matthew Rojas',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 102',
      'Ship To - Country': 'US',
      'Order - Number': 1574,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Jacob Burrows',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE 102/870',
      'Ship To - Country': 'US',
      'Order - Number': 1573,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Roy Wohlers',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE 102/870',
      'Ship To - Country': 'US',
      'Order - Number': 1572,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Joshua Smith',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 102',
      'Ship To - Country': 'US',
      'Order - Number': 1571,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 4XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Joshua Smith',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 102',
      'Ship To - Country': 'US',
      'Order - Number': 1571,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 4XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's Cooling Performance T-Shirt",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'Austin Tell',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1569,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Graphite',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies Cooling Performance T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-NW3201-Graphite',
      'Ship To - Name': 'Virginia Pablo-Pablo',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 101',
      'Ship To - Country': 'US',
      'Order - Number': 1578,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Small, Color: Graphite',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Michael Iuliano',
      'Ship To - Address 1': '3350 W LIBERTY RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 824',
      'Ship To - Country': 'US',
      'Order - Number': 1582,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'William Sullivan',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 900',
      'Ship To - Country': 'US',
      'Order - Number': 1584,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Long Sleeve Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'David Gadziemski',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 213',
      'Ship To - Country': 'US',
      'Order - Number': 1591,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Eric Jones',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO-WARES',
      'Ship To - Country': 'US',
      'Order - Number': 1594,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Joshua Hart',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 900',
      'Ship To - Country': 'US',
      'Order - Number': 1593,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 4XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Tyrone Tate',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO-WARES',
      'Ship To - Country': 'US',
      'Order - Number': 1592,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Robert Lee',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 900',
      'Ship To - Country': 'US',
      'Order - Number': 1596,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Tall Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Roger Worthington',
      'Ship To - Address 1': '213 S WALNUT ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 230',
      'Ship To - Country': 'US',
      'Order - Number': 1601,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XT, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Tall Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Greg Joice',
      'Ship To - Address 1': '213 S WALNUT ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO PARTS CENTER',
      'Ship To - Country': 'US',
      'Order - Number': 1599,
      'Date - Shipped Date': '7/1/2021 7:59:25 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XT, Color: Red',
    },
  ];
  constructor() {}

  ngOnInit(): void {}

  // tslint:disable-next-line:typedef
  downloadFile(data: any) {
    const replacer = (key, value) => (value === null ? '' : value); // specify how you want to handle null values here
    const header = Object.keys(data[0]);
    const csv = data.map((row) =>
      header
        .map((fieldName) => JSON.stringify(row[fieldName], replacer))
        .join(',')
    );
    csv.unshift(header.join(','));
    const csvArray = csv.join('\r\n');
    const a = document.createElement('a');
    const blob = new Blob([csvArray], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    a.href = url;
    a.download = 'Shipments-07-01.csv';
    a.click();
    window.URL.revokeObjectURL(url);
    a.remove();
  }

  public removeSlashes(side: string): string {
    if (side) {
      side.replace(/\//g, '');
      return side.replace('<br/>', '');
    }
  }
}
