import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-invoice0520',
  templateUrl: './invoice0520.component.html',
  styleUrls: ['./invoice0520.component.css']
})
export class Invoice0520Component implements OnInit {
  twenty: any = [
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20W-RED',
      'Ship To - Name': 'Brenda Culver',
      'Ship To - Address 1': '133 S MAIN ST # 15',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1385,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20LW-RED',
      'Ship To - Name': 'Brenda Culver',
      'Ship To - Address 1': '133 S MAIN ST # 15',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1385,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Linda Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1389,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Linda Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1389,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Linda Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1389,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Charcoal'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Joe Skarritt',
      'Ship To - Address 1': '3501 W HIGHLAND RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE MILFORD',
      'Ship To - Country': 'US',
      'Order - Number': 1393,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Red'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': 'linda j 1st shift',
      'Item - Qty': 4,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Adriana Loredo-Banda',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1392,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Small, Color: Charcoal'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt',
      'Notes - From Buyer': 'linda j 1st shift',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55LS-Graphite',
      'Ship To - Name': 'Adriana Loredo-Banda',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1392,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Small, Color: Charcoal'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt',
      'Notes - From Buyer': 'linda j 1st shift',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55LS-Graphite',
      'Ship To - Name': 'John Gleason',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 101',
      'Ship To - Country': 'US',
      'Order - Number': 1391,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Charcoal'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': 'linda j 1st shift',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'John Gleason',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 101',
      'Ship To - Country': 'US',
      'Order - Number': 1391,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Charcoal'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s Cooling Performance T-Shirt',
      'Notes - From Buyer': 'linda j 1st shift',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'Alison Knapp',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1390,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Graphite'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies Cooling Performance T-Shirt',
      'Notes - From Buyer': 'linda j 1st shift',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-NW3201-Graphite',
      'Ship To - Name': 'Alison Knapp',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1390,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Graphite'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': 'linda j 1st shift',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Alison Knapp',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1390,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Charcoal'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Budd Greenman',
      'Ship To - Address 1': '613 N STATE ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTOVALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1394,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Red'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Nicholas Smit',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 507',
      'Ship To - Country': 'US',
      'Order - Number': 1395,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: LT, Color: Red'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20W-RED',
      'Ship To - Name': 'Holly Rocheleau',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 231',
      'Ship To - Country': 'US',
      'Order - Number': 1398,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Red'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Suzanne Clark',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 231',
      'Ship To - Country': 'US',
      'Order - Number': 1397,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Daniel Nickens',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 231',
      'Ship To - Country': 'US',
      'Order - Number': 1399,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XT, Color: Red'
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20W-RED',
      'Ship To - Name': 'Cynthia Gilkerson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 440',
      'Ship To - Country': 'US',
      'Order - Number': 1400,
      'Date - Shipped Date': '5/20/2021 5:02:39 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Small, Color: Red'
    },
    {
      'Amount - Order Total': 101.5,
      'Item - Name': 'Devon & Jones Ladies Three-Season Classic Jacket - Large / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 307',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403277-D700W-AVPS-L',
      'Ship To - Name': 'Ron  Shockey',
      'Ship To - Address 1': '1367 N LEROY ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV FENTON',
      'Ship To - Country': 'US',
      'Order - Number': 1090,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 101.5,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 101.5,
      'Item - Name': 'Devon & Jones Men\'s Three-Season Classic Jacket - X-Large / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 307',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-AVPS-XL',
      'Ship To - Name': 'Ron  Shockey',
      'Ship To - Address 1': '1367 N LEROY ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV FENTON',
      'Ship To - Country': 'US',
      'Order - Number': 1090,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 101.5,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 571.75,
      'Item - Name': 'Men\'s Cooling Performance T-Shirt - Medium / Graphite',
      'Notes - From Buyer': 'Shawn Rasmussen 2XL cotton (5) and 2XL Hoodie\nAaron Snowden XL cotton (5) and XL Hoodie\nMarissa Moore XL cotton (5) and L Hoodie\nBrittany Gresley L cotton (3) L Dri Release women\'s (2) and XL Hoodie\nMichael Abdo 2XL Dri Release (3) 2XL cotton (2) and 2XL Hoodie\nMadison Amos  2XL Mens Dri Release (5) Aand 3XL Hoodie\nGavin Machida S cotton (5) and S Hoodie\nConner Kline M cotton (3) M Dri Release (2) and L Hoodie<br/>Store Number/Name: 870',
      'Item - Qty': 2,
      'Item - Price': 9.5,
      'Item - SKU': '403201-N3142-AWGC-M',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1091,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 571.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 571.75,
      'Item - Name': 'P&C Core Blend T-Shirt - Medium / Charcoal',
      'Notes - From Buyer': 'Shawn Rasmussen 2XL cotton (5) and 2XL Hoodie\nAaron Snowden XL cotton (5) and XL Hoodie\nMarissa Moore XL cotton (5) and L Hoodie\nBrittany Gresley L cotton (3) L Dri Release women\'s (2) and XL Hoodie\nMichael Abdo 2XL Dri Release (3) 2XL cotton (2) and 2XL Hoodie\nMadison Amos  2XL Mens Dri Release (5) Aand 3XL Hoodie\nGavin Machida S cotton (5) and S Hoodie\nConner Kline M cotton (3) M Dri Release (2) and L Hoodie<br/>Store Number/Name: 870',
      'Item - Qty': 3,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-M',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1091,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 571.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 571.75,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - Small / Charcoal',
      'Notes - From Buyer': 'Shawn Rasmussen 2XL cotton (5) and 2XL Hoodie\nAaron Snowden XL cotton (5) and XL Hoodie\nMarissa Moore XL cotton (5) and L Hoodie\nBrittany Gresley L cotton (3) L Dri Release women\'s (2) and XL Hoodie\nMichael Abdo 2XL Dri Release (3) 2XL cotton (2) and 2XL Hoodie\nMadison Amos  2XL Mens Dri Release (5) Aand 3XL Hoodie\nGavin Machida S cotton (5) and S Hoodie\nConner Kline M cotton (3) M Dri Release (2) and L Hoodie<br/>Store Number/Name: 870',
      'Item - Qty': 1,
      'Item - Price': 24.5,
      'Item - SKU': '403197-PC90H-AWGC-S',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1091,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 571.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 571.75,
      'Item - Name': 'P&C Core Blend T-Shirt - Small / Charcoal',
      'Notes - From Buyer': 'Shawn Rasmussen 2XL cotton (5) and 2XL Hoodie\nAaron Snowden XL cotton (5) and XL Hoodie\nMarissa Moore XL cotton (5) and L Hoodie\nBrittany Gresley L cotton (3) L Dri Release women\'s (2) and XL Hoodie\nMichael Abdo 2XL Dri Release (3) 2XL cotton (2) and 2XL Hoodie\nMadison Amos  2XL Mens Dri Release (5) Aand 3XL Hoodie\nGavin Machida S cotton (5) and S Hoodie\nConner Kline M cotton (3) M Dri Release (2) and L Hoodie<br/>Store Number/Name: 870',
      'Item - Qty': 5,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-S',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1091,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 571.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 571.75,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - 3XL / Charcoal',
      'Notes - From Buyer': 'Shawn Rasmussen 2XL cotton (5) and 2XL Hoodie\nAaron Snowden XL cotton (5) and XL Hoodie\nMarissa Moore XL cotton (5) and L Hoodie\nBrittany Gresley L cotton (3) L Dri Release women\'s (2) and XL Hoodie\nMichael Abdo 2XL Dri Release (3) 2XL cotton (2) and 2XL Hoodie\nMadison Amos  2XL Mens Dri Release (5) Aand 3XL Hoodie\nGavin Machida S cotton (5) and S Hoodie\nConner Kline M cotton (3) M Dri Release (2) and L Hoodie<br/>Store Number/Name: 870',
      'Item - Qty': 1,
      'Item - Price': 32.5,
      'Item - SKU': '403197-PC90H-AWGC-3X',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1091,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 571.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 571.75,
      'Item - Name': 'Men\'s Cooling Performance T-Shirt - 2XL / Graphite',
      'Notes - From Buyer': 'Shawn Rasmussen 2XL cotton (5) and 2XL Hoodie\nAaron Snowden XL cotton (5) and XL Hoodie\nMarissa Moore XL cotton (5) and L Hoodie\nBrittany Gresley L cotton (3) L Dri Release women\'s (2) and XL Hoodie\nMichael Abdo 2XL Dri Release (3) 2XL cotton (2) and 2XL Hoodie\nMadison Amos  2XL Mens Dri Release (5) Aand 3XL Hoodie\nGavin Machida S cotton (5) and S Hoodie\nConner Kline M cotton (3) M Dri Release (2) and L Hoodie<br/>Store Number/Name: 870',
      'Item - Qty': 8,
      'Item - Price': 12.5,
      'Item - SKU': '403201-N3142-AWGC-2XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1091,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 571.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 571.75,
      'Item - Name': 'P&C Core Blend T-Shirt - Large / Charcoal',
      'Notes - From Buyer': 'Shawn Rasmussen 2XL cotton (5) and 2XL Hoodie\nAaron Snowden XL cotton (5) and XL Hoodie\nMarissa Moore XL cotton (5) and L Hoodie\nBrittany Gresley L cotton (3) L Dri Release women\'s (2) and XL Hoodie\nMichael Abdo 2XL Dri Release (3) 2XL cotton (2) and 2XL Hoodie\nMadison Amos  2XL Mens Dri Release (5) Aand 3XL Hoodie\nGavin Machida S cotton (5) and S Hoodie\nConner Kline M cotton (3) M Dri Release (2) and L Hoodie<br/>Store Number/Name: 870',
      'Item - Qty': 3,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-L',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1091,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 571.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 571.75,
      'Item - Name': 'Ladies Cooling Performance T-Shirt - Large / Graphite',
      'Notes - From Buyer': 'Shawn Rasmussen 2XL cotton (5) and 2XL Hoodie\nAaron Snowden XL cotton (5) and XL Hoodie\nMarissa Moore XL cotton (5) and L Hoodie\nBrittany Gresley L cotton (3) L Dri Release women\'s (2) and XL Hoodie\nMichael Abdo 2XL Dri Release (3) 2XL cotton (2) and 2XL Hoodie\nMadison Amos  2XL Mens Dri Release (5) Aand 3XL Hoodie\nGavin Machida S cotton (5) and S Hoodie\nConner Kline M cotton (3) M Dri Release (2) and L Hoodie<br/>Store Number/Name: 870',
      'Item - Qty': 2,
      'Item - Price': 9.75,
      'Item - SKU': '403196-NW3201-AWGC-L',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1091,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 571.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 571.75,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - Large / Charcoal',
      'Notes - From Buyer': 'Shawn Rasmussen 2XL cotton (5) and 2XL Hoodie\nAaron Snowden XL cotton (5) and XL Hoodie\nMarissa Moore XL cotton (5) and L Hoodie\nBrittany Gresley L cotton (3) L Dri Release women\'s (2) and XL Hoodie\nMichael Abdo 2XL Dri Release (3) 2XL cotton (2) and 2XL Hoodie\nMadison Amos  2XL Mens Dri Release (5) Aand 3XL Hoodie\nGavin Machida S cotton (5) and S Hoodie\nConner Kline M cotton (3) M Dri Release (2) and L Hoodie<br/>Store Number/Name: 870',
      'Item - Qty': 2,
      'Item - Price': 24.5,
      'Item - SKU': '403197-PC90H-AWGC-L',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1091,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 571.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 571.75,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - X-Large / Charcoal',
      'Notes - From Buyer': 'Shawn Rasmussen 2XL cotton (5) and 2XL Hoodie\nAaron Snowden XL cotton (5) and XL Hoodie\nMarissa Moore XL cotton (5) and L Hoodie\nBrittany Gresley L cotton (3) L Dri Release women\'s (2) and XL Hoodie\nMichael Abdo 2XL Dri Release (3) 2XL cotton (2) and 2XL Hoodie\nMadison Amos  2XL Mens Dri Release (5) Aand 3XL Hoodie\nGavin Machida S cotton (5) and S Hoodie\nConner Kline M cotton (3) M Dri Release (2) and L Hoodie<br/>Store Number/Name: 870',
      'Item - Qty': 2,
      'Item - Price': 24.5,
      'Item - SKU': '403197-PC90H-AWGC-XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1091,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 571.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 571.75,
      'Item - Name': 'P&C Core Blend T-Shirt - X-Large / Charcoal',
      'Notes - From Buyer': 'Shawn Rasmussen 2XL cotton (5) and 2XL Hoodie\nAaron Snowden XL cotton (5) and XL Hoodie\nMarissa Moore XL cotton (5) and L Hoodie\nBrittany Gresley L cotton (3) L Dri Release women\'s (2) and XL Hoodie\nMichael Abdo 2XL Dri Release (3) 2XL cotton (2) and 2XL Hoodie\nMadison Amos  2XL Mens Dri Release (5) Aand 3XL Hoodie\nGavin Machida S cotton (5) and S Hoodie\nConner Kline M cotton (3) M Dri Release (2) and L Hoodie<br/>Store Number/Name: 870',
      'Item - Qty': 10,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1091,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 571.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 571.75,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - 2XL / Charcoal',
      'Notes - From Buyer': 'Shawn Rasmussen 2XL cotton (5) and 2XL Hoodie\nAaron Snowden XL cotton (5) and XL Hoodie\nMarissa Moore XL cotton (5) and L Hoodie\nBrittany Gresley L cotton (3) L Dri Release women\'s (2) and XL Hoodie\nMichael Abdo 2XL Dri Release (3) 2XL cotton (2) and 2XL Hoodie\nMadison Amos  2XL Mens Dri Release (5) Aand 3XL Hoodie\nGavin Machida S cotton (5) and S Hoodie\nConner Kline M cotton (3) M Dri Release (2) and L Hoodie<br/>Store Number/Name: 870',
      'Item - Qty': 2,
      'Item - Price': 31.5,
      'Item - SKU': '403197-PC90H-AWGC-2X',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1091,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 571.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 571.75,
      'Item - Name': 'P&C Core Blend T-Shirt - 2XL / Charcoal',
      'Notes - From Buyer': 'Shawn Rasmussen 2XL cotton (5) and 2XL Hoodie\nAaron Snowden XL cotton (5) and XL Hoodie\nMarissa Moore XL cotton (5) and L Hoodie\nBrittany Gresley L cotton (3) L Dri Release women\'s (2) and XL Hoodie\nMichael Abdo 2XL Dri Release (3) 2XL cotton (2) and 2XL Hoodie\nMadison Amos  2XL Mens Dri Release (5) Aand 3XL Hoodie\nGavin Machida S cotton (5) and S Hoodie\nConner Kline M cotton (3) M Dri Release (2) and L Hoodie<br/>Store Number/Name: 870',
      'Item - Qty': 7,
      'Item - Price': 9.75,
      'Item - SKU': '403198-PC55-AWGC-2X',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': '1902-12',
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 571.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 15.5,
      'Item - Name': 'P&C Essential Fleece Crewneck Sweatshirt - Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 500 Madison WI warehouse',
      'Item - Qty': 1,
      'Item - Price': 15.5,
      'Item - SKU': '403200-PC90-AWGC-L',
      'Ship To - Name': 'Joe Duane',
      'Ship To - Address 1': '816 W MAIN ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1094,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 15.5,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 50.75,
      'Item - Name': 'Devon & Jones Men\'s Three-Season Classic Jacket - Large / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 227',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-AVPS-L',
      'Ship To - Name': 'Dustin Huggins',
      'Ship To - Address 1': '1130 W 7TH ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV MONROE',
      'Ship To - Country': 'US',
      'Order - Number': 1093,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 50.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 64.25,
      'Item - Name': 'P&C Core Blend T-Shirt - 4XL / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 521',
      'Item - Qty': 3,
      'Item - Price': 10.25,
      'Item - SKU': '403198-PC55-AWGC-4X',
      'Ship To - Name': 'Daniel Eckert',
      'Ship To - Address 1': '6229 CROSS CREEK BLVD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1092,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 64.25,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 64.25,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - 4XL / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 521',
      'Item - Qty': 1,
      'Item - Price': 33.5,
      'Item - SKU': '403197-PC90H-AWGC-4X',
      'Ship To - Name': 'Daniel Eckert',
      'Ship To - Address 1': '6229 CROSS CREEK BLVD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1092,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 64.25,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 40.85,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt - Medium / Charcoal',
      'Notes - From Buyer': 'Katie Jeremiah Welsh<br/>Store Number/Name: 135',
      'Item - Qty': 1,
      'Item - Price': 9.35,
      'Item - SKU': '403199-PC55LS-AWGC-M',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1095,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 40.85,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 40.85,
      'Item - Name': 'P&C Core Blend T-Shirt - Medium / Charcoal',
      'Notes - From Buyer': 'Katie Jeremiah Welsh<br/>Store Number/Name: 135',
      'Item - Qty': 1,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-M',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1095,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 40.85,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 40.85,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - Medium / Charcoal',
      'Notes - From Buyer': 'Katie Jeremiah Welsh<br/>Store Number/Name: 135',
      'Item - Qty': 1,
      'Item - Price': 24.5,
      'Item - SKU': '403197-PC90H-AWGC-M',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1095,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 40.85,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 50.75,
      'Item - Name': 'Devon & Jones Men\'s Three-Season Classic Jacket - X-Large / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 325',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-AVPS-XL',
      'Ship To - Name': 'James Dorsey',
      'Ship To - Address 1': '15600 MIDDLEBELT RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV LIVONIA #1',
      'Ship To - Country': 'US',
      'Order - Number': 1098,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 50.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 52.75,
      'Item - Name': 'Devon & Jones Ladies Three-Season Classic Jacket - 2XL / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 379',
      'Item - Qty': 1,
      'Item - Price': 52.75,
      'Item - SKU': '403277-D700W-AVPS-2X',
      'Ship To - Name': 'Dana Rau',
      'Ship To - Address 1': '441 E MAIN ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV HARTFORD',
      'Ship To - Country': 'US',
      'Order - Number': 1097,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 52.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 50.75,
      'Item - Name': 'Devon & Jones Men\'s Three-Season Classic Jacket - X-Large / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 506',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-AVPS-XL',
      'Ship To - Name': 'Duane Dykhouse',
      'Ship To - Address 1': '3849 OAKES ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV GRANDVILLE',
      'Ship To - Country': 'US',
      'Order - Number': 1096,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 50.75,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    },
    {
      'Amount - Order Total': 46.5,
      'Item - Name': 'P&C Essential Fleece Crewneck Sweatshirt - X-Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: Port Huron 218',
      'Item - Qty': 3,
      'Item - Price': 15.5,
      'Item - SKU': '403200-PC90-AWGC-XL',
      'Ship To - Name': 'JEFF King',
      'Ship To - Address 1': '2035 16TH ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1100,
      'Date - Shipped Date': '5/20/2021 4:58:49 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 46.5,
      'Item - Fill SKU': '',
      'Item - Options': 'See Sku'
    }
  ];

  constructor() { }

  ngOnInit(): void {
  }

  // tslint:disable-next-line:typedef
  downloadFile(data: any) {
    const replacer = (key, value) => (value === null ? '' : value); // specify how you want to handle null values here
    const header = Object.keys(data[0]);
    const csv = data.map((row) =>
      header
        .map((fieldName) => JSON.stringify(row[fieldName], replacer))
        .join(',')
    );
    csv.unshift(header.join(','));
    const csvArray = csv.join('\r\n');
    const a = document.createElement('a');
    const blob = new Blob([csvArray], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    a.href = url;
    a.download = 'Shipments-05-20.csv';
    a.click();
    window.URL.revokeObjectURL(url);
    a.remove();
  }

  public removeSlashes(side: string): string {
    if (side) {
      side.replace(/\//g, '');
      return side.replace('<br/>', '');
    }
  }

}
