import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-invoice0622',
  templateUrl: './invoice0622.component.html',
  styleUrls: ['./invoice0622.component.css'],
})
export class Invoice0622Component implements OnInit {
  twentytwo: any = [
    {
      'Amount - Order Total': 55.75,
      'Item - Name': 'P&C Core Blend T-Shirt - 6XL / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 870',
      'Item - Qty': 5,
      'Item - Price': 11.15,
      'Item - SKU': '403198-PC55-AWGC-6X',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1110,
      'Date - Shipped Date': '6/22/2021 2:32:10 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 55.75,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 74,
      'Item - Name': "Men's CrownLux Performance Plaited Tall Polo - LT / Red",
      'Notes - From Buyer': '<br/>Store Number/Name: 612',
      'Item - Qty': 2,
      'Item - Price': 37,
      'Item - SKU': '403288-DG20T-BTB-LT',
      'Ship To - Name': 'Rick Parks',
      'Ship To - Address 1': '6982 HERON WAY',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1114,
      'Date - Shipped Date': '6/22/2021 2:32:10 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 74,
      'Item - Fill SKU': '',
      'Item - Options': 'Right Sleeve Co-Op: Gates',
    },
    {
      'Amount - Order Total': 103.5,
      'Item - Name':
        "Devon & Jones Men's Three-Season Classic Jacket - 3XL / Black",
      'Notes - From Buyer': '<br/>Store Number/Name: 521',
      'Item - Qty': 1,
      'Item - Price': 52.75,
      'Item - SKU': '403195-D700-AVPS-3X',
      'Ship To - Name': 'Thomas Applegate',
      'Ship To - Address 1': '6229 CROSS CREEK BLVD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV FT WAYNE',
      'Ship To - Country': 'US',
      'Order - Number': 1116,
      'Date - Shipped Date': '6/22/2021 2:32:10 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 103.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 103.5,
      'Item - Name':
        "Devon & Jones Men's Three-Season Classic Jacket - X-Large / Black",
      'Notes - From Buyer': '<br/>Store Number/Name: 521',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-AVPS-XL',
      'Ship To - Name': 'Thomas Applegate',
      'Ship To - Address 1': '6229 CROSS CREEK BLVD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV FT WAYNE',
      'Ship To - Country': 'US',
      'Order - Number': 1116,
      'Date - Shipped Date': '6/22/2021 2:32:10 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 103.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 50.75,
      'Item - Name':
        "Devon & Jones Men's Three-Season Classic Jacket - X-Large / Black",
      'Notes - From Buyer': '<br/>Store Number/Name: 244',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-AVPS-XL',
      'Ship To - Name': 'Kevin Miller',
      'Ship To - Address 1': '4980 PARK LAKE RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV EAST LANSING',
      'Ship To - Country': 'US',
      'Order - Number': 1115,
      'Date - Shipped Date': '6/22/2021 2:32:10 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 50.75,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'A1-DG20P-NAVY',
      'Ship To - Name': 'TYLIN TYLIN',
      'Ship To - Address 1': '11159 W CARSON CITY RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTOVALUE 216',
      'Ship To - Country': 'US',
      'Order - Number': 1455,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Navy',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'TYLIN TYLIN',
      'Ship To - Address 1': '11159 W CARSON CITY RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTOVALUE 216',
      'Ship To - Country': 'US',
      'Order - Number': 1455,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'A1-DG20W-NAVY',
      'Ship To - Name': 'JillAnn Collins',
      'Ship To - Address 1': '11159 W CARSON CITY RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 216',
      'Ship To - Country': 'US',
      'Order - Number': 1454,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Navy',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Denise Hernandez',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 498',
      'Ship To - Country': 'US',
      'Order - Number': 1473,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Denise Hernandez',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 498',
      'Ship To - Country': 'US',
      'Order - Number': 1473,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '1ST SHIFT LINDA J',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Linda Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1472,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '1ST SHIFT LINDA J',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Linda Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1477,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '1ST SHIFT LINDA J',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Linda Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1477,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's Cooling Performance T-Shirt",
      'Notes - From Buyer': '1ST SHIFT LINDA J',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'Linda Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1477,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Graphite',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Long Sleeve Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'Sara Walters Walters',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE BACK STORE',
      'Ship To - Country': 'US',
      'Order - Number': 1480,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Sara Walters Walters',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE BACK STORE',
      'Ship To - Country': 'US',
      'Order - Number': 1480,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Tall Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 6,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'George West',
      'Ship To - Address 1': '811 N STATE ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE STANTON',
      'Ship To - Country': 'US',
      'Order - Number': 1481,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XT, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Christine Vanhoven',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 265',
      'Ship To - Country': 'US',
      'Order - Number': 1486,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Thomas Isenga',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 265',
      'Ship To - Country': 'US',
      'Order - Number': 1485,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Eric Vanhoven',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 265',
      'Ship To - Country': 'US',
      'Order - Number': 1484,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Edward Schief',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 265',
      'Ship To - Country': 'US',
      'Order - Number': 1483,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Danielle Smith',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 265',
      'Ship To - Country': 'US',
      'Order - Number': 1482,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's Cooling Performance T-Shirt",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'Evan Bunting',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1488,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Graphite',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Alex Bunting',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1487,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's Cooling Performance T-Shirt",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'Alex Bunting',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1487,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Graphite',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'rodney swalley',
      'Ship To - Address 1': '601 S STATE ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'OSCODA',
      'Ship To - Country': 'US',
      'Order - Number': 1492,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Ken Friend',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1496,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Tall Long Sleeve Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 4,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20LT-RED',
      'Ship To - Name': 'Clifton Barker',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE JACKSON 270',
      'Ship To - Country': 'US',
      'Order - Number': 1495,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XT, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Long Sleeve Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'Caleb Pilaczynski',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE STORE - 361',
      'Ship To - Country': 'US',
      'Order - Number': 1499,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Caleb Pilaczynski',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE STORE - 361',
      'Ship To - Country': 'US',
      'Order - Number': 1499,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Long Sleeve Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'Xavier Ruggles',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE STORE - 361',
      'Ship To - Country': 'US',
      'Order - Number': 1498,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 4,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Xavier Ruggles',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE STORE - 361',
      'Ship To - Country': 'US',
      'Order - Number': 1498,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'George West',
      'Ship To - Address 1': '811 N STATE ST # 357',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 357',
      'Ship To - Country': 'US',
      'Order - Number': 1500,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Pat Carlson',
      'Ship To - Address 1': '10 W M35',
      'Ship To - Address 2': 'PO BOX 940',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1502,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20P-RED',
      'Ship To - Name': 'Jacob Staley',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 824',
      'Ship To - Country': 'US',
      'Order - Number': 1505,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 6,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Josh staley',
      'Ship To - Address 1': '3350 W LIBERTY RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1504,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Thomas metz',
      'Ship To - Address 1': '3350 W LIBERTY RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1503,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Kirkland Schneider',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1506,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's Cooling Performance T-Shirt",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'Kirkland Schneider',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1506,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Graphite',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 4,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Kirkland Schneider',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1506,
      'Date - Shipped Date': '6/22/2021 8:08:11 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Charcoal',
    },
  ];
  constructor() {}

  ngOnInit(): void {}

  // tslint:disable-next-line:typedef
  downloadFile(data: any) {
    const replacer = (key, value) => (value === null ? '' : value); // specify how you want to handle null values here
    const header = Object.keys(data[0]);
    const csv = data.map((row) =>
      header
        .map((fieldName) => JSON.stringify(row[fieldName], replacer))
        .join(',')
    );
    csv.unshift(header.join(','));
    const csvArray = csv.join('\r\n');
    const a = document.createElement('a');
    const blob = new Blob([csvArray], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    a.href = url;
    a.download = 'Shipments-06-22.csv';
    a.click();
    window.URL.revokeObjectURL(url);
    a.remove();
  }

  public removeSlashes(side: string): string {
    if (side) {
      side.replace(/\//g, '');
      return side.replace('<br/>', '');
    }
  }
}
