import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-invoice0',
  templateUrl: './invoice0.component.html',
  styleUrls: ['./invoice0.component.css']
})
export class Invoice0Component implements OnInit {
  zero: any = [
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - Medium / Charcoal',
      'Notes - From Buyer': 'Coldwater Warehouse; Attn Shanti Kling',
      'Item - Qty': 0,
      'Item - Price': 24.5,
      'Item - SKU': '403197-PC90H-M',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1032,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 293.6
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s Cooling Performance T-Shirt - Small / Graphite',
      'Notes - From Buyer': 'Coldwater Warehouse; Attn Shanti Kling',
      'Item - Qty': 0,
      'Item - Price': 9.5,
      'Item - SKU': '403201-N3142-S',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1032,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 293.6
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt - 2XL / Charcoal',
      'Notes - From Buyer': 'Coldwater Warehouse; Attn Shanti Kling',
      'Item - Qty': 0,
      'Item - Price': 12.5,
      'Item - SKU': '403199-PC55LS-2XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1032,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 293.6
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt - 2XL / Charcoal',
      'Notes - From Buyer': 'Coldwater Warehouse; Attn Shanti Kling',
      'Item - Qty': 0,
      'Item - Price': 9.75,
      'Item - SKU': '403198-PC55-2XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1032,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 293.6
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt - Medium / Charcoal',
      'Notes - From Buyer': 'Coldwater Warehouse; Attn Shanti Kling',
      'Item - Qty': 0,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-M',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1032,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 293.6
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt - Medium / Charcoal',
      'Notes - From Buyer': 'Coldwater Warehouse; Attn Shanti Kling',
      'Item - Qty': 0,
      'Item - Price': 9.35,
      'Item - SKU': '403199-PC55LS-M',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1032,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 293.6
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - 3XL / Charcoal',
      'Notes - From Buyer': 'Coldwater Warehouse; Attn Shanti Kling',
      'Item - Qty': 0,
      'Item - Price': 32.5,
      'Item - SKU': '403197-PC90H-3XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1032,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 293.6
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt - 3XL / Charcoal',
      'Notes - From Buyer': 'Coldwater Warehouse; Attn Shanti Kling',
      'Item - Qty': 0,
      'Item - Price': 10.15,
      'Item - SKU': '403198-PC55-3XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1032,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 293.6
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - Large / Charcoal',
      'Notes - From Buyer': 'Coldwater Warehouse; Attn Shanti Kling',
      'Item - Qty': 0,
      'Item - Price': 24.5,
      'Item - SKU': '403197-PC90H-L',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1032,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 293.6
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - 2XL / Charcoal',
      'Notes - From Buyer': 'Coldwater Warehouse; Attn Shanti Kling',
      'Item - Qty': 0,
      'Item - Price': 31.5,
      'Item - SKU': '403197-PC90H-2XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1032,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 293.6
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - X-Large / Red',
      'Notes - From Buyer': 'AV508\nKenowa Auto Value - Dorr, MI',
      'Item - Qty': 0,
      'Item - Price': 35.5,
      'Item - SKU': '403272-DG20P-AV-XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1031,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 319.5
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - Medium / Red',
      'Notes - From Buyer': 'AV508\nKenowa Auto Value - Dorr, MI',
      'Item - Qty': 0,
      'Item - Price': 35.5,
      'Item - SKU': '403272-DG20P-AV-M',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1031,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 319.5
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - 5XL / Red',
      'Notes - From Buyer': 'AV307\nRonald Shockey',
      'Item - Qty': 0,
      'Item - Price': 40.5,
      'Item - SKU': '403272-DG20P-AV-5XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1028,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 227
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - Large / Red',
      'Notes - From Buyer': 'AV307\nRonald Shockey',
      'Item - Qty': 0,
      'Item - Price': 35.5,
      'Item - SKU': '403272-DG20P-AV-L',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1028,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 227
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - 2XL / Red',
      'Notes - From Buyer': 'AV307\nRonald Shockey',
      'Item - Qty': 0,
      'Item - Price': 37.5,
      'Item - SKU': '403272-DG20P-AV-2XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1028,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 227
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - Medium / Red',
      'Notes - From Buyer': 'Auto Value Highland \nAttn Don McGuire',
      'Item - Qty': 0,
      'Item - Price': 35.5,
      'Item - SKU': '403272-DG20P-AV-M',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1027,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 355
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - X-Large / Red',
      'Notes - From Buyer': 'Auto Value Highland \nAttn Don McGuire',
      'Item - Qty': 0,
      'Item - Price': 35.5,
      'Item - SKU': '403272-DG20P-AV-XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1027,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 355
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt - X-Large / Charcoal',
      'Notes - From Buyer': 'AWI GR Attn Connie Redmond',
      'Item - Qty': 0,
      'Item - Price': 7,
      'Item - SKU': '403198-XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1024,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 21
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - X-Large / Red',
      'Notes - From Buyer': 'Richard Roberts; Store 111',
      'Item - Qty': 0,
      'Item - Price': 35.5,
      'Item - SKU': '403272-AV-XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1023,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 106.5
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Devon & Jones Men\'s Three-Season Classic Jacket - 3XL / Black',
      'Notes - From Buyer': 'Large for Mathew Robbins AV Battle Creek; Large for 267 AV Romeo; XL for Alexander LaBean 507 Byron Center; 3XL for 616 BTB Heartford',
      'Item - Qty': 0,
      'Item - Price': 52.75,
      'Item - SKU': '403195-BTB-3X',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1011,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 205
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Devon & Jones Men\'s Three-Season Classic Jacket - X-Large / Black',
      'Notes - From Buyer': 'Large for Mathew Robbins AV Battle Creek; Large for 267 AV Romeo; XL for Alexander LaBean 507 Byron Center; 3XL for 616 BTB Heartford',
      'Item - Qty': 0,
      'Item - Price': 50.75,
      'Item - SKU': '403195-AV-XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1011,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 205
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Devon & Jones Men\'s Three-Season Classic Jacket - Large / Black',
      'Notes - From Buyer': 'Large for Mathew Robbins AV Battle Creek; Large for 267 AV Romeo; XL for Alexander LaBean 507 Byron Center; 3XL for 616 BTB Heartford',
      'Item - Qty': 0,
      'Item - Price': 50.75,
      'Item - SKU': '403195-AV-L',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1011,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 205
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt - 3XL / Charcoal',
      'Notes - From Buyer': 'AWI Coldwater 102; Attn Matt Rojas',
      'Item - Qty': 0,
      'Item - Price': 32.5,
      'Item - SKU': '403197-3XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'Auto Value Grand Ledge',
      'Ship To - Country': 'US',
      'Order - Number': 1010,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 62.95
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt - 3XL / Charcoal',
      'Notes - From Buyer': 'AWI Coldwater 102; Attn Matt Rojas',
      'Item - Qty': 0,
      'Item - Price': 10.15,
      'Item - SKU': '403198-3XL',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'Auto Value Grand Ledge',
      'Ship To - Country': 'US',
      'Order - Number': 1010,
      'Date - Shipped Date': '',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 62.95
    }
  ];

  constructor() { }

  ngOnInit(): void {
    console.log(this.zero);
  }

    // tslint:disable-next-line:typedef
    downloadFile(data: any) {
      const replacer = (key, value) => (value === null ? '' : value); // specify how you want to handle null values here
      const header = Object.keys(data[0]);
      const csv = data.map((row) =>
        header
          .map((fieldName) => JSON.stringify(row[fieldName], replacer))
          .join(',')
      );
      csv.unshift(header.join(','));
      const csvArray = csv.join('\r\n');
      const a = document.createElement('a');
      const blob = new Blob([csvArray], { type: 'text/csv' });
      const url = window.URL.createObjectURL(blob);
      a.href = url;
      a.download = 'Shipments-03-26.csv';
      a.click();
      window.URL.revokeObjectURL(url);
      a.remove();
    }

    public removeSlashes(side: string): string {
      if (side) {
        side.replace(/\//g, '');
        return side.replace('<br/>', '');
      }
    }

}
