import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-invoice0709',
  templateUrl: './invoice0709.component.html',
  styleUrls: ['./invoice0709.component.css'],
})
export class Invoice0709Component implements OnInit {
  julnine: any = [
    {
      'Amount - Order Total': 50.75,
      'Item - Name':
        "Devon & Jones Men's Three-Season Classic Jacket - X-Large / Black",
      'Notes - From Buyer': '<br/>Store Number/Name: 216',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-AVPS-XL',
      'Ship To - Name': 'Tylin Sherman',
      'Ship To - Address 1': '11159 W CARSON CITY RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV GREENVILLE',
      'Ship To - Country': 'US',
      'Order - Number': 1138,
      'Date - Shipped Date': '7/9/2021 6:37:41 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 50.75,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 50.75,
      'Item - Name':
        "Devon & Jones Men's Three-Season Classic Jacket - Medium / Black",
      'Notes - From Buyer': '<br/>Store Number/Name: 385',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-AVPS-M',
      'Ship To - Name': 'Jeff Olsen',
      'Ship To - Address 1': '2000 LUDINGTON ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV ESCANABA',
      'Ship To - Country': 'US',
      'Order - Number': 1137,
      'Date - Shipped Date': '7/9/2021 6:37:41 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 50.75,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 30.5,
      'Item - Name': 'P&C Core Blend T-Shirt - Small / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 330 NEWBERRY',
      'Item - Qty': 2,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-S',
      'Ship To - Name': 'Gordon Fergin',
      'Ship To - Address 1': '7595 Michigan 123',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1142,
      'Date - Shipped Date': '7/9/2021 6:37:41 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 30.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 30.5,
      'Item - Name': "Men's Cooling Performance T-Shirt - X-Large / Graphite",
      'Notes - From Buyer': '<br/>Store Number/Name: 330 NEWBERRY',
      'Item - Qty': 1,
      'Item - Price': 9.5,
      'Item - SKU': '403201-N3142-AWGC-XL',
      'Ship To - Name': 'Gordon Fergin',
      'Ship To - Address 1': '7595 Michigan 123',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1142,
      'Date - Shipped Date': '7/9/2021 6:37:41 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 30.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 30.5,
      'Item - Name': 'P&C Core Blend T-Shirt - X-Large / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 330 NEWBERRY',
      'Item - Qty': 1,
      'Item - Price': 7,
      'Item - SKU': '403198-PC55-AWGC-XL',
      'Ship To - Name': 'Gordon Fergin',
      'Ship To - Address 1': '7595 Michigan 123',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1142,
      'Date - Shipped Date': '7/9/2021 6:37:41 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 30.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 52.75,
      'Item - Name':
        "Devon & Jones Men's Three-Season Classic Jacket - 2XL / Black",
      'Notes - From Buyer': '<br/>Store Number/Name: 220',
      'Item - Qty': 1,
      'Item - Price': 52.75,
      'Item - SKU': '403195-D700-AVPS-2X',
      'Ship To - Name': 'Sethe Clement',
      'Ship To - Address 1': '1070 W LAKE ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV TAWAS CITY',
      'Ship To - Country': 'US',
      'Order - Number': 1141,
      'Date - Shipped Date': '7/9/2021 6:37:41 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 52.75,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 71,
      'Item - Name':
        "Men's CrownLux Performance Plaited Polo with Pocket - Large / Red",
      'Notes - From Buyer': '<br/>Store Number/Name: 612',
      'Item - Qty': 2,
      'Item - Price': 35.5,
      'Item - SKU': '403272-DG20P-BTB-L',
      'Ship To - Name': 'Rick Parks',
      'Ship To - Address 1': '6982 HERON WAY',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1143,
      'Date - Shipped Date': '7/9/2021 6:37:41 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 71,
      'Item - Fill SKU': '',
      'Item - Options': 'Right Sleeve Co-Op: Gates',
    },
    {
      'Amount - Order Total': 101.5,
      'Item - Name':
        "Devon & Jones Men's Three-Season Classic Jacket - Large / Black",
      'Notes - From Buyer': '<br/>Store Number/Name: 623',
      'Item - Qty': 2,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-BTB-L',
      'Ship To - Name': 'Martin Vanderwerf',
      'Ship To - Address 1': '27640 75TH ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'BTB SALEM',
      'Ship To - Country': 'US',
      'Order - Number': 1145,
      'Date - Shipped Date': '7/9/2021 6:37:41 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 101.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 52.75,
      'Item - Name':
        "Devon & Jones Men's Three-Season Classic Jacket - 3XL / Black",
      'Notes - From Buyer': '<br/>Store Number/Name: 298',
      'Item - Qty': 1,
      'Item - Price': 52.75,
      'Item - SKU': '403195-D700-AVPS-3X',
      'Ship To - Name': 'Brian Verschueren',
      'Ship To - Address 1': '7737 LAKE ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AV BEAR LAKE',
      'Ship To - Country': 'US',
      'Order - Number': 1144,
      'Date - Shipped Date': '7/9/2021 6:37:41 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 52.75,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'edwin birdsley',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTOWARES',
      'Ship To - Country': 'US',
      'Order - Number': 1628,
      'Date - Shipped Date': '7/9/2021 6:41:48 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'AUTO VALUE FORT WAYNE',
      'Ship To - Address 1': '6229 CROSS CREEK BLVD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1634,
      'Date - Shipped Date': '7/9/2021 6:41:48 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Bradley Webb',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 521',
      'Ship To - Country': 'US',
      'Order - Number': 1633,
      'Date - Shipped Date': '7/9/2021 6:41:48 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'David Gillingham',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 521',
      'Ship To - Country': 'US',
      'Order - Number': 1632,
      'Date - Shipped Date': '7/9/2021 6:41:48 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 4XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Tall Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'chris brenner',
      'Ship To - Address 1': '309 S SUPERIOR ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE ALBION',
      'Ship To - Country': 'US',
      'Order - Number': 1630,
      'Date - Shipped Date': '7/9/2021 6:41:48 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XT, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20W-RED',
      'Ship To - Name': 'Chelsea Newman',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE BACK STORE',
      'Ship To - Country': 'US',
      'Order - Number': 1640,
      'Date - Shipped Date': '7/9/2021 6:41:48 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20W-RED',
      'Ship To - Name': 'Briana-Rishane Nelmark',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 234',
      'Ship To - Country': 'US',
      'Order - Number': 1638,
      'Date - Shipped Date': '7/9/2021 6:41:48 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'AUTO VALUE FORT WAYNE',
      'Ship To - Address 1': '6229 CROSS CREEK BLVD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1637,
      'Date - Shipped Date': '7/9/2021 6:41:48 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 4XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'AUTO VALUE FORT WAYNE',
      'Ship To - Address 1': '6229 CROSS CREEK BLVD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1637,
      'Date - Shipped Date': '7/9/2021 6:41:48 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Red',
    },
  ];
  constructor() {}

  ngOnInit(): void {}

  // tslint:disable-next-line:typedef
  downloadFile(data: any) {
    const replacer = (key, value) => (value === null ? '' : value); // specify how you want to handle null values here
    const header = Object.keys(data[0]);
    const csv = data.map((row) =>
      header
        .map((fieldName) => JSON.stringify(row[fieldName], replacer))
        .join(',')
    );
    csv.unshift(header.join(','));
    const csvArray = csv.join('\r\n');
    const a = document.createElement('a');
    const blob = new Blob([csvArray], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    a.href = url;
    a.download = 'Shipments-07-09.csv';
    a.click();
    window.URL.revokeObjectURL(url);
    a.remove();
  }

  public removeSlashes(side: string): string {
    if (side) {
      side.replace(/\//g, '');
      return side.replace('<br/>', '');
    }
  }
}
