import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-invoice0630',
  templateUrl: './invoice0630.component.html',
  styleUrls: ['./invoice0630.component.css'],
})
export class Invoice0630Component implements OnInit {
  thirty: any = [
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Richard Lawrence',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1513,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's Cooling Performance T-Shirt",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'William Morrison',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1512,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Graphite',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Laronda Legrand',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1511,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Laronda Legrand',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1511,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Michael Jones',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1510,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Michael Jones',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1510,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's Cooling Performance T-Shirt",
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'Michael Cupples',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1509,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Graphite',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55LS-Graphite',
      'Ship To - Name': 'Michael Cupples',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1509,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Isaac Thomas',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1508,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Isaac Thomas',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1508,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Gary Moore',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1517,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Patricia Bojko',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1516,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Small, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 4,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Ashlynn Graham',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1515,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Ashlynn Graham',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1515,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55LS-Graphite',
      'Ship To - Name': 'Kaitlyn Pangman',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1514,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Kaitlyn Pangman',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1514,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Antwan Bonds',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1533,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Shirley Allen',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1531,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Small, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Sam Vitanovski',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1530,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 4XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'May Gerhold',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1529,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Chandler Wise',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1528,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Karen Faucher',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1526,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Jonathan Panoff',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1525,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Thomas Nowak',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1524,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': 'annual',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Ramone Hicks',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1523,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 4XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Gage Wheeler',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1540,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Kristeen Hargrove',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1539,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Nicole LaForte',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1538,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Robert Chabot',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1535,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Jacqueline Breen',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1534,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Marvin Fleming',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1549,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Trevor Fate',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 147',
      'Ship To - Country': 'US',
      'Order - Number': 1548,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's Cooling Performance T-Shirt",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'Steve LaBean',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 108',
      'Ship To - Country': 'US',
      'Order - Number': 1544,
      'Date - Shipped Date': '6/30/2021 2:09:06 PM',
      'Custom - Field 1': 'AW Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Graphite',
    },
  ];

  constructor() {}

  ngOnInit(): void {}

  // tslint:disable-next-line:typedef
  downloadFile(data: any) {
    const replacer = (key, value) => (value === null ? '' : value); // specify how you want to handle null values here
    const header = Object.keys(data[0]);
    const csv = data.map((row) =>
      header
        .map((fieldName) => JSON.stringify(row[fieldName], replacer))
        .join(',')
    );
    csv.unshift(header.join(','));
    const csvArray = csv.join('\r\n');
    const a = document.createElement('a');
    const blob = new Blob([csvArray], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    a.href = url;
    a.download = 'Shipments-06-30.csv';
    a.click();
    window.URL.revokeObjectURL(url);
    a.remove();
  }

  public removeSlashes(side: string): string {
    if (side) {
      side.replace(/\//g, '');
      return side.replace('<br/>', '');
    }
  }
}
