import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-invoice0513',
  templateUrl: './invoice0513.component.html',
  styleUrls: ['./invoice0513.component.css']
})
export class Invoice0513Component implements OnInit {
  thirteen: any = [
    {
      'Amount - Order Total': 50.75,
      'Item - Name': 'Devon & Jones Ladies Three-Season Classic Jacket - Medium / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 290',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403277-D700W-AVPS-M',
      'Ship To - Name': 'Kelley Reade',
      'Ship To - Address 1': '97 S MICHIGAN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1069,
      'Date - Shipped Date': '5/13/2021 6:49:28 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 50.75,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 177.5,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - Medium / Red',
      'Notes - From Buyer': 'Cristian Marin<br/>Store Number/Name: 101',
      'Item - Qty': 5,
      'Item - Price': 35.5,
      'Item - SKU': '403272-DG20P-AVPS-M',
      'Ship To - Name': 'Katie Barone',
      'Ship To - Address 1': '440 Kirkland St. SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1087,
      'Date - Shipped Date': '5/13/2021 6:49:28 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 177.5,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 160.45,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket - Medium / Red',
      'Notes - From Buyer': '<br/>Store Number/Name: 313',
      'Item - Qty': 1,
      'Item - Price': 35.5,
      'Item - SKU': '403272-DG20P-AVPS-M',
      'Ship To - Name': 'Greg Paquin',
      'Ship To - Address 1': '2307 S DUNDEE CT',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1088,
      'Date - Shipped Date': '5/13/2021 6:49:28 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 160.45,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 160.45,
      'Item - Name': 'North End Men\'s Flux Mélange Bonded Fleece Jacket - Medium / Carbon/Oly Red / Auto-Wares Group of Companies',
      'Notes - From Buyer': '<br/>Store Number/Name: 313',
      'Item - Qty': 1,
      'Item - Price': 70,
      'Item - SKU': '403244-88697-AWGC-M',
      'Ship To - Name': 'Greg Paquin',
      'Ship To - Address 1': '2307 S DUNDEE CT',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1088,
      'Date - Shipped Date': '5/13/2021 6:49:28 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 160.45,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 160.45,
      'Item - Name': 'Devon & Jones Men\'s Three-Season Classic Jacket - Medium / Black',
      'Notes - From Buyer': '<br/>Store Number/Name: 313',
      'Item - Qty': 1,
      'Item - Price': 50.75,
      'Item - SKU': '403195-D700-AVPS-M',
      'Ship To - Name': 'Greg Paquin',
      'Ship To - Address 1': '2307 S DUNDEE CT',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1088,
      'Date - Shipped Date': '5/13/2021 6:49:28 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 160.45,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 66,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo - Medium / Red',
      'Notes - From Buyer': 'For AprilBurtn<br/>Store Number/Name: 212',
      'Item - Qty': 2,
      'Item - Price': 33,
      'Item - SKU': '403275-DG20W-AVPS-M',
      'Ship To - Name': 'April Burton',
      'Ship To - Address 1': '7085 ROUND HILL DR APT B1',
      'Ship To - Address 2': 'B1',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1089,
      'Date - Shipped Date': '5/13/2021 6:49:28 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 66,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Gary Rohder',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 245',
      'Ship To - Country': 'US',
      'Order - Number': 1362,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'David Bouwkamp',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 511',
      'Ship To - Country': 'US',
      'Order - Number': 1368,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'David Bouwkamp',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 511',
      'Ship To - Country': 'US',
      'Order - Number': 1368,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'David Bouwkamp',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 511',
      'Ship To - Country': 'US',
      'Order - Number': 1368,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Tall Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 4,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'RICHARD VERHEY',
      'Ship To - Address 1': 'O-217 LAKE MICHIGAN DR NW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTOWARES / KENOWA AUTO VALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1367,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'RICHARD VERHEY',
      'Ship To - Address 1': 'O-217 LAKE MICHIGAN DR NW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTOWARES / KENOWA AUTO VALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1367,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Mark Antcliff',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 511',
      'Ship To - Country': 'US',
      'Order - Number': 1365,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Dale Daggett',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 244',
      'Ship To - Country': 'US',
      'Order - Number': 1372,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20P-RED',
      'Ship To - Name': 'Otis Smith',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'BTB 479',
      'Ship To - Country': 'US',
      'Order - Number': 1379,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20P-RED',
      'Ship To - Name': 'Javier Duarte',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'BTB 479',
      'Ship To - Country': 'US',
      'Order - Number': 1378,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Bob Elert',
      'Ship To - Address 1': '3501 W HIGHLAND RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1380,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'Danny Hutcherson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 245',
      'Ship To - Country': 'US',
      'Order - Number': 1382,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Thomas Teets',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 253',
      'Ship To - Country': 'US',
      'Order - Number': 1381,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20W-RED',
      'Ship To - Name': 'Pam Wright',
      'Ship To - Address 1': '10870 AMBER RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE - LUDINGTON',
      'Ship To - Country': 'US',
      'Order - Number': 1383,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Polo with Pocket',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20P-RED',
      'Ship To - Name': 'Rodney Dorr',
      'Ship To - Address 1': '1107 W MAIN ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'BUMPER TO BUMPER',
      'Ship To - Country': 'US',
      'Order - Number': 1384,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20L-RED',
      'Ship To - Name': 'Rodney Dorr',
      'Ship To - Address 1': '1107 W MAIN ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'BUMPER TO BUMPER',
      'Ship To - Country': 'US',
      'Order - Number': 1384,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Men\'s CrownLux Performance Plaited Long Sleeve Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20L-RED',
      'Ship To - Name': 'Douglas Roberts',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 349',
      'Ship To - Country': 'US',
      'Order - Number': 1386,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20W-RED',
      'Ship To - Name': 'Janice Peckham',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 663',
      'Ship To - Country': 'US',
      'Order - Number': 1387,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 4,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20W-RED',
      'Ship To - Name': 'Chris Cicotte',
      'Ship To - Address 1': '24600 GRATIOT AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1388,
      'Date - Shipped Date': '5/13/2021 6:53:02 PM',
      'Custom - Field 1': '',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': ''
    }
  ];

  constructor() { }

  ngOnInit(): void {
  }

   // tslint:disable-next-line:typedef
   downloadFile(data: any) {
    const replacer = (key, value) => (value === null ? '' : value); // specify how you want to handle null values here
    const header = Object.keys(data[0]);
    const csv = data.map((row) =>
      header
        .map((fieldName) => JSON.stringify(row[fieldName], replacer))
        .join(',')
    );
    csv.unshift(header.join(','));
    const csvArray = csv.join('\r\n');
    const a = document.createElement('a');
    const blob = new Blob([csvArray], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    a.href = url;
    a.download = 'Shipments-05-13.csv';
    a.click();
    window.URL.revokeObjectURL(url);
    a.remove();
  }

  public removeSlashes(side: string): string {
    if (side) {
      side.replace(/\//g, '');
      return side.replace('<br/>', '');
    }
  }

}
