import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-invoice0610',
  templateUrl: './invoice0610.component.html',
  styleUrls: ['./invoice0610.component.css'],
})
export class Invoice0610Component implements OnInit {
  sixten: any = [
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'GREG BAILER',
      'Ship To - Address 1': '6944 12TH AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'KENOWA AUTO VALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1423,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20P-RED',
      'Ship To - Name': 'Steven Groat',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 636',
      'Ship To - Country': 'US',
      'Order - Number': 1440,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20P-RED',
      'Ship To - Name': 'William Lang',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 431',
      'Ship To - Country': 'US',
      'Order - Number': 1444,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'BTOB-DG20P-RED',
      'Ship To - Name': 'Mark Shipman',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 431',
      'Ship To - Country': 'US',
      'Order - Number': 1443,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'SG-DG20P-RED',
      'Ship To - Name': 'scott s',
      'Ship To - Address 1': '108 W CARPENTER ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VLAUE',
      'Ship To - Country': 'US',
      'Order - Number': 1451,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Tall Polo",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20T-RED',
      'Ship To - Name': 'Koby Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 519',
      'Ship To - Country': 'US',
      'Order - Number': 1459,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: LT, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies CrownLux Performance Plaited Polo',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20W-RED',
      'Ship To - Name': "Melissa O'Callaghan",
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 273',
      'Ship To - Country': 'US',
      'Order - Number': 1463,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 4,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Billy Lawler',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 273',
      'Ship To - Country': 'US',
      'Order - Number': 1462,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Lawrence Fiebig',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'STORE NUMBER 273',
      'Ship To - Country': 'US',
      'Order - Number': 1461,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Graham Eley',
      'Ship To - Address 1': '125 S MICHIGAN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1466,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's Cooling Performance T-Shirt",
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'Graham Eley',
      'Ship To - Address 1': '125 S MICHIGAN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1466,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Graphite',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Graham Eley',
      'Ship To - Address 1': '125 S MICHIGAN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1466,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's Cooling Performance T-Shirt",
      'Notes - From Buyer': '',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'Hunter Roussey',
      'Ship To - Address 1': '125 S MICHIGAN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1465,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Graphite',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Hunter Roussey',
      'Ship To - Address 1': '125 S MICHIGAN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1465,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Crewneck Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90-Charcoal',
      'Ship To - Name': 'Hunter Roussey',
      'Ship To - Address 1': '125 S MICHIGAN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1465,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's Cooling Performance T-Shirt",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'Bryan Foote',
      'Ship To - Address 1': '125 S MICHIGAN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1464,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Graphite',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Crewneck Sweatshirt',
      'Notes - From Buyer': '',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90-Charcoal',
      'Ship To - Name': 'Bryan Foote',
      'Ship To - Address 1': '125 S MICHIGAN AVE',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': '',
      'Ship To - Country': 'US',
      'Order - Number': 1464,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'PATRICK LOVE',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE COLDWATER',
      'Ship To - Country': 'US',
      'Order - Number': 1467,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '1ST SHIFT LINDA J',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Linda Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1468,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Large, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '1ST SHIFT LINDA J',
      'Item - Qty': 2,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Linda Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1470,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '1ST SHIFT LINDA J',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Linda Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1470,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 2XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's Cooling Performance T-Shirt",
      'Notes - From Buyer': '1ST SHIFT LINDA J',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-N3142-Graphite',
      'Ship To - Name': 'Linda Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1469,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 4XL, Color: Graphite',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Essential Fleece Pullover Hooded Sweatshirt',
      'Notes - From Buyer': '1st shift linda j',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC90H-Graphite',
      'Ship To - Name': 'Linda Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1471,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Long Sleeve Core Blend T-Shirt',
      'Notes - From Buyer': '1st shift linda j',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55LS-Graphite',
      'Ship To - Name': 'Linda Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1471,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Small, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '1st shift linda j',
      'Item - Qty': 1,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Linda Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1471,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Medium, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 5,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'jeff halfmann',
      'Ship To - Address 1': '1320 WASHINGTON ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'CIRCLE AUTO PARTS',
      'Ship To - Country': 'US',
      'Order - Number': 1475,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 3XL, Color: Red',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'P&C Core Blend T-Shirt',
      'Notes - From Buyer': '1ST SHIFT LINDA J',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-PC55-Graphite',
      'Ship To - Name': 'Linda Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1478,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: 4XL, Color: Charcoal',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': 'Ladies Cooling Performance T-Shirt',
      'Notes - From Buyer': '1ST SHIFT LINDA J',
      'Item - Qty': 3,
      'Item - Price': 0,
      'Item - SKU': 'AUTOWARESGROUP-NW3201-Graphite',
      'Ship To - Name': 'Linda Johnson',
      'Ship To - Address 1': '440 KIRTLAND ST SW',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO WARES INC',
      'Ship To - Country': 'US',
      'Order - Number': 1476,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: Small, Color: Graphite',
    },
    {
      'Amount - Order Total': 0,
      'Item - Name': "Men's CrownLux Performance Plaited Polo with Pocket",
      'Notes - From Buyer': '',
      'Item - Qty': 4,
      'Item - Price': 0,
      'Item - SKU': 'AUTOVALUE-DG20P-RED',
      'Ship To - Name': 'Mike Denney',
      'Ship To - Address 1': '1070 W LAKE ST',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AUTO VALUE',
      'Ship To - Country': 'US',
      'Order - Number': 1479,
      'Date - Shipped Date': '6/10/2021 7:14:48 PM',
      'Custom - Field 1': 'Anniversary',
      'Amount - Paid by Customer': 0,
      'Item - Fill SKU': '',
      'Item - Options': 'Size: X-Large, Color: Red',
    },
    {
      'Amount - Order Total': 19.5,
      'Item - Name': 'P&C Core Blend T-Shirt - 2XL / Charcoal',
      'Notes - From Buyer': '<br/>Store Number/Name: 362',
      'Item - Qty': 2,
      'Item - Price': 9.75,
      'Item - SKU': '403198-PC55-AWGC-2X',
      'Ship To - Name': 'Mike Schneider',
      'Ship To - Address 1': '8377 DELAND RD',
      'Ship To - Address 2': '',
      'Ship To - Address 3': '',
      'Ship To - Company': 'AWI',
      'Ship To - Country': 'US',
      'Order - Number': 1112,
      'Date - Shipped Date': '6/10/2021 7:11:52 PM',
      'Custom - Field 1': 'Shopify',
      'Amount - Paid by Customer': 19.5,
      'Item - Fill SKU': '',
      'Item - Options': '',
    },
  ];

  constructor() {}

  ngOnInit(): void {}

  // tslint:disable-next-line:typedef
  downloadFile(data: any) {
    const replacer = (key, value) => (value === null ? '' : value); // specify how you want to handle null values here
    const header = Object.keys(data[0]);
    const csv = data.map((row) =>
      header
        .map((fieldName) => JSON.stringify(row[fieldName], replacer))
        .join(',')
    );
    csv.unshift(header.join(','));
    const csvArray = csv.join('\r\n');
    const a = document.createElement('a');
    const blob = new Blob([csvArray], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    a.href = url;
    a.download = 'Shipments-06-10.csv';
    a.click();
    window.URL.revokeObjectURL(url);
    a.remove();
  }

  public removeSlashes(side: string): string {
    if (side) {
      side.replace(/\//g, '');
      return side.replace('<br/>', '');
    }
  }
}
